# these keys will in particular contribute to filenames, so they have dashes instead of underscores.
art_styles = {
    "pop": "pop art",
    "psychedelic": "psychedelic art",
    "visionary": "visionary art",
    "manga": "manga & anime",
    "impressionism": "impressionism",
    "victorian": "Victorian-era illustration",
    "thai-temple": "Thai temple murals",
    "islamic-geometric": "Islamic geometric patterns",
    "turkish-marbling": "Turkish marbling",
    "watercolor": "watercolor painting",
    "pointillism": "pointillism",
    "cubism": "cubism",
    "abstract": "abstract art",
    "surrealism": "surrealism",
    "neoexpressionism": "neo-expressionism",
    "sepia-pencil": "sepia-tone pencil drawings",
    "fauvism": "fauvism",
    "cave": "cave painting",
    "magical-realism": "magical realism",
    "chinese-cubism": "chinese cubism",
    "mishe": "mishe technique",
    "pollock": "Jackson Pollock",
    "basquiat": "Jean-Michel Basquiat",
    "midcentury-modern": "mid-century modern",
    "art-nouveau": "art nouveau",
    "japanese-woodblock": "ukiyo-e (Japanese woodblock)",
    "japanese-ink-wash": "sumi-e (Japanese ink wash)",
    "batik": "batik",
    "lanna": "Lanna (from the Lanna Kingdom)",
    "neobaroque": "neo-baroque",
    "hopper": "Edward Hopper",
    "italian-futurism": "Italian futurism",
    "new-yorker": "New Yorker cartoons",
    "miro": "Joan Miro",
    "tomine": "Adrian Tomine",
    "picasso": "Pablo Picasso",
    "mondrian": "Piet Mondrian",
    "van-gogh": "Vincent van Gogh",
    "arrival": "The Arrival, by Shaun Tam"
}