# these are organized alphabetically by destination name.
inputs = [
    # {
    #     "destination": "algarve",
    #     "destination_fullname": "The Algarve, Portugal",
    #     "transport_method": "rental car for coastal drives",
    #     "requested_sightseeing_stops": "a boat trip to explore sea caves with an amiable captain",
    #     "tour_guide": None,
    #     "season": "spring",
    # },
    # {
    #     "destination": "amalfi",
    #     "destination_fullname": "Amalfi Coast, Italy",
    #     "transport_method": "Vespa (an Italian motor scooter)",
    #     "requested_sightseeing_stops": "coastal boat tour with a friendly captain",
    #     "tour_guide": None,
    #     "season": "spring",
    # },
    # {
    #     "destination": "bali",
    #     "destination_fullname": "Bali, Indonesia",
    #     "transport_method": "car with a young woman driver who is also a tour guide and also rental scooters",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": None,
    #     "season": "spring",
    # },
    # {
    #     "destination": "bangkok",
    #     "destination_fullname": "Bangkok, Thailand",
    #     "transport_method": "tuk-tuk (i.e. a rickshaw)",
    #     "requested_sightseeing_stops": "Chatuchak weekend market",
    #     "tour_guide": "our tuk-tuk driver",
    #     "season": "winter",
    # },
    # {
    #     "destination": "barcelona",
    #     "destination_fullname": "Barcelona, Spain",
    #     "transport_method": "guided bike tour",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": "an affable university student who double-majors in art and history as a tour guide",
    #     "season": "early fall",
    # },
    # {
    #     "destination": "berkeley",
    #     "destination_fullname": "Berkeley, California",
    #     "transport_method": "a Prius (a hybrid car)",
    #     "requested_sightseeing_stops": "a hike in Tilden Park",
    #     "tour_guide": None,
    #     "season": "spring",
    # },
    # {
    #     "destination": "chiangmai",
    #     "destination_fullname": "Chiang Mai, Thailand",
    #     "transport_method": "tuk-tuk (i.e. rickshaw)",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": None,
    #     "season": "winter",
    # },
    {
        "destination": "cinqueterre",
        "destination_fullname": "Cinque Terre, Italy",
        "transport_method": "a leisurely boat trip",
        "requested_sightseeing_stops": "hiking the trails between the villages",
        "tour_guide": None,
        "season": "spring",
    },
    # {
    #     "destination": "costarica",
    #     "destination_fullname": "Costa Rica",
    #     "transport_method": "camper van",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": None,
    #     "season": "dry season",
    # },
    # {
    #     "destination": "dubai",
    #     "destination_fullname": "Dubai, United Arab Emirates",
    #     "transport_method": "private limousine",
    #     "requested_sightseeing_stops": "a ride in an abra (i.e. a traditional boat) on Dubai Creek",
    #     "tour_guide": None,
    #     "season": "winter",
    # },
    # {
    #     "destination": "greece",
    #     "destination_fullname": "Greece",
    #     "transport_method": "catamaran",
    #     "requested_sightseeing_stops": "a donkey ride on Santorini",
    #     "tour_guide": "catamaran captain",
    #     "season": "spring",
    # },
    # {
    #     "destination": "istanbul",
    #     "destination_fullname": "Istanbul, Turkey",
    #     "transport_method": "ferry ride on the Bosphorous",
    #     "requested_sightseeing_stops": "riding the historic tram on Istiklal Avenue",
    #     "tour_guide": None,
    #     "season": "spring",
    # },
    # {
    #     "destination": "kyoto",
    #     "destination_fullname": "Kyoto, Japan",
    #     "transport_method": "rickshaw",
    #     "requested_sightseeing_stops": "bicycling from Kyoto Station to the Kyoto Botanical Gardens along the Kamo-gawa River",
    #     "tour_guide": "our rickshaw driver, a jovial middle-aged man",
    #     "season": "spring",
    # },
    # {
    #     "destination": "london",
    #     "destination_fullname": "London, England",
    #     "transport_method": "the Tube subway, and also a double-decker bus",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": "the driver of our double-decker bus, a middle-aged British man with an attention to detail that rivals Sherlock Holmes",
    #     "season": "spring",
    # },
    # {
    #     "destination": "napa",
    #     "destination_fullname": "Napa Valley, California",
    #     "transport_method": "wine train",
    #     "requested_sightseeing_stops": "a ride in a hot air balloon",
    #     "tour_guide": None,
    #     "season": "fall",
    # },
    # {
    #     "destination": "newyorkcity",
    #     "destination_fullname": "New York, New York",
    #     "transport_method": "open-top bus tour and Metro",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": "a middle-aged man with a thick Brooklyn accent whose family has been in New York City for many generations",
    #     "season": "fall",
    # },
    # {
    #     "destination": "paris",
    #     "destination_fullname": "Paris, France",
    #     "transport_method": "Seine river cruise and Paris Metro",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": "a man in his early 40s who wears a beret and neckerchief and speaks with just a slight French accent",
    #     "season": "spring",
    # },
    # {
    #     "destination": "queenstown",
    #     "destination_fullname": "Queenstown, New Zealand",
    #     "transport_method": "water taxis",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": None,
    #     "season": "summer",
    # },
    # {
    #     "destination": "rio",
    #     "destination_fullname": "Rio de Janeiro, Brazil",
    #     "transport_method": "limousine",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": "our limousine driver, a quiet but friendly man in his early 50s who is aging gracefully",
    #     "season": "late spring",
    # },
    # {
    #     "destination": "shanghai",
    #     "destination_fullname": "Shanghai, China",
    #     "transport_method": "Shanghai Metro",
    #     "requested_sightseeing_stops": "a Huangpu River cruise",
    #     "tour_guide": None,
    #     "season": "fall",
    # },
    # {
    #     "destination": "tokyo",
    #     "destination_fullname": "Tokyo, Japan",
    #     "transport_method": "Tokyo metro train and Toei subway system",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": "a gregarious but soft-spoken young woman",
    #     "season": "spring",
    # },
]