# these are organized alphabetically by destination name.
inputs = {
    # "algarve": {
    #     "destination": "algarve",
    #     "destination_fullname": "The Algarve, Portugal",
    #     "transport_method": "rental car",
    #     "requested_sightseeing_stops": "a drive along the coast and a boat trip to explore sea caves with an amiable captain",
    #     "tour_guide": None,
    #     "season": "spring",
    #     "art_style": "fauvism",
    # },
    # "amalfi": {
    #     "destination": "amalfi",
    #     "destination_fullname": "Amalfi Coast, Italy",
    #     "transport_method": "Vespa (an Italian motor scooter)",
    #     "requested_sightseeing_stops": "coastal boat tour with a friendly captain",
    #     "tour_guide": None,
    #     "season": "spring",
    #     "art_style": "van-gogh",
    # },
    # "bali": {
    #     "destination": "bali",
    #     "destination_fullname": "Bali, Indonesia",
    #     "transport_method": "car with driver and rental scooters",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": "the young woman who is driving our car",
    #     "season": "spring",
    #     "art_style": "batik",
    # },
    # "bangkok": {
    #     "destination": "bangkok",
    #     "destination_fullname": "Bangkok, Thailand",
    #     "transport_method": "tuk-tuk (i.e. a rickshaw)",
    #     "requested_sightseeing_stops": "Chatuchak weekend market",
    #     "tour_guide": "our tuk-tuk driver",
    #     "season": "winter",
    #     "art_style": "thai-temple",
    # },
    # "barcelona": {
    #     "destination": "barcelona",
    #     "destination_fullname": "Barcelona, Spain",
    #     "transport_method": "guided bike tour",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": "an affable university student who double-majors in art and history",
    #     "season": "early fall",
    #     "art_style": "miro",
    # },
    # "berkeley": {
    #     "destination": "berkeley",
    #     "destination_fullname": "Berkeley, California",
    #     "transport_method": "a Prius (a hybrid car)",
    #     "requested_sightseeing_stops": "a hike in Tilden Park",
    #     "tour_guide": None,
    #     "season": "spring",
    #     "art_style": "art-nouveau",
    # },
    # "chiangmai": {
    #     "destination": "chiangmai",
    #     "destination_fullname": "Chiang Mai, Thailand",
    #     "transport_method": "tuk-tuk (i.e. rickshaw)",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": None,
    #     "season": "winter",
    #     "art_style": "lanna",
    # },
    # "cinqueterre": {
    #     "destination": "cinqueterre",
    #     "destination_fullname": "Cinque Terre, Italy",
    #     "transport_method": "a leisurely boat trip",
    #     "requested_sightseeing_stops": "hiking the trails between the villages",
    #     "tour_guide": None,
    #     "season": "spring",
    #     "art_style": "cave",
    # },
    # "costarica": {
    #     "destination": "costarica",
    #     "destination_fullname": "Costa Rica",
    #     "transport_method": "camper van",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": None,
    #     "season": "dry season",
    #     "art_style": "watercolor",
    # },
    # "dubai": {
    #     "destination": "dubai",
    #     "destination_fullname": "Dubai, United Arab Emirates",
    #     "transport_method": "private limousine",
    #     "requested_sightseeing_stops": "a ride in an abra (i.e. a traditional boat) on Dubai Creek",
    #     "tour_guide": None,
    #     "season": "winter",
    #     "art_style": "visionary",
    # },
    # "greece": {
    #     "destination": "greece",
    #     "destination_fullname": "Greece",
    #     "transport_method": "catamaran",
    #     "requested_sightseeing_stops": "a donkey ride on Santorini",
    #     "tour_guide": "catamaran captain",
    #     "season": "spring",
    #     "art_style": "pointillism",
    # },
    # "istanbul": {
    #     "destination": "istanbul",
    #     "destination_fullname": "Istanbul, Turkey",
    #     "transport_method": "ferry ride on the Bosphorous",
    #     "requested_sightseeing_stops": "riding the historic tram on Istiklal Avenue",
    #     "tour_guide": None,
    #     "season": "spring",
    #     "art_style": "islamic-geometric",
    # },
    # "kyoto": {
    #     "destination": "kyoto",
    #     "destination_fullname": "Kyoto, Japan",
    #     "transport_method": "rickshaw",
    #     "requested_sightseeing_stops": "bicycling from Kyoto Station to the Kyoto Botanical Gardens along the Kamo-gawa River",
    #     "tour_guide": "our rickshaw driver, a jovial middle-aged man",
    #     "season": "spring",
    #     "art_style": "japanese-woodblock",
    # },
    # "london": {
    #     "destination": "london",
    #     "destination_fullname": "London, England",
    #     "transport_method": "the Tube subway, and also a double-decker bus",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": "the driver of our double-decker bus, a middle-aged British man with an attention to detail that rivals Sherlock Holmes",
    #     "season": "spring",
    #     "art_style": "victorian",
    # },
    # "napa": {
    #     "destination": "napa",
    #     "destination_fullname": "Napa Valley, California",
    #     "transport_method": "wine train",
    #     "requested_sightseeing_stops": "a ride in a hot air balloon",
    #     "tour_guide": None,
    #     "season": "fall",
    #     "art_style": "cubism",
    # },
    # "newyorkcity": {
    #     "destination": "newyorkcity",
    #     "destination_fullname": "New York, New York",
    #     "transport_method": "open-top bus tour and Metro",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": "a middle-aged man with a thick Brooklyn accent whose family has been in New York City for many generations",
    #     "season": "fall",
    #     "art_style": "pop",
    # },
    # "paris": {
    #     "destination": "paris",
    #     "destination_fullname": "Paris, France",
    #     "transport_method": "Seine river cruise and Paris Metro",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": "a man in his early 40s who wears a beret and neckerchief and speaks with just a slight French accent",
    #     "season": "spring",
    #     "art_style": "neobaroque",
    # },
    # "queenstown": {
    #     "destination": "queenstown",
    #     "destination_fullname": "Queenstown, New Zealand",
    #     "transport_method": "water taxis",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": None,
    #     "season": "summer",
    #     "art_style": "retrofuturism",
    # },
    # "rio": {
    #     "destination": "rio",
    #     "destination_fullname": "Rio de Janeiro, Brazil",
    #     "transport_method": "limousine",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": "our limousine driver, a quiet but friendly man in his early 50s who is aging gracefully",
    #     "season": "late spring",
    #     "art_style": "mondrian",
    # },
    # "shanghai": {
    #     "destination": "shanghai",
    #     "destination_fullname": "Shanghai, China",
    #     "transport_method": "Shanghai Metro",
    #     "requested_sightseeing_stops": "a Huangpu River cruise",
    #     "tour_guide": None,
    #     "season": "fall",
    #     "art_style": "tomine",
    # },
    # "tokyo": {
    #     "destination": "tokyo",
    #     "destination_fullname": "Tokyo, Japan",
    #     "transport_method": "Tokyo metro train and Toei subway system",
    #     "requested_sightseeing_stops": None,
    #     "tour_guide": "a gregarious but soft-spoken young woman",
    #     "season": "spring",
    #     "art_style": "manga",
    # },
    "seattle": {
        "destination": "seattle",
        "destination_fullname": "Seattle, Washington",
        "transport_method": "rental car",
        "requested_sightseeing_stops": None,
        "tour_guide": "a confident young woman who is a journalist for the Seattle Times newspaper and also gives tours to share her love for her city",
        "season": "springtime, on a day that is mostly sunny but with scattered showers (which we are prepared for with our rain jackets and umbrellas and which make everything gleam beautifully)",
        "art_style": "chihuly",
    },
    "arizona": {
        "destination": "arizona",
        "destination_fullname": "Arizona",
        "transport_method": "Jeep Wrangler",
        "requested_sightseeing_stops": None,
        "tour_guide": None,
        "season": "early springtime",
        "art_style": "navajo",
    },
    "yucatan": {
        "destination": "yucatan",
        "destination_fullname": "Yucatan Peninsula, Mexico",
        "transport_method": "minibus",
        "requested_sightseeing_stops": None,
        "tour_guide": None,
        "season": "summer",
        "art_style": "mayan",
    },
    "vienna": {
        "destination": "vienna",
        "destination_fullname": "Vienna, Austria",
        "transport_method": "bicycle",
        "requested_sightseeing_stops": None,
        "tour_guide": "a renowned historian and opera critic",
        "season": "season",
        "art_style": "neobaroque",
    },
    "budapest": {
        "destination": "budapest",
        "destination_fullname": "Budapest, Hungary",
        "transport_method": "metro",
        "requested_sightseeing_stops": "thermal baths",
        "tour_guide": None,
        "season": "springtime",
        "art_style": "sepia-pencil",
    },
    "taipei": {
        "destination": "taipei",
        "destination_fullname": "Taipei, Taiwan",
        "transport_method": "subway",
        "requested_sightseeing_stops": None,
        "tour_guide": None,
        "season": "early springtime, with flowers just beginning to bloom",
        "art_style": "chinese-ink-wash",
    },
    "nepal": {
        "destination": "nepal",
        "destination_fullname": "Nepal",
        "transport_method": "bus",
        "requested_sightseeing_stops": None,
        "tour_guide": None,
        "season": "autumn (which is festival season)",
        "art_style": "mithila",
    },
    "hawaii": {
        "destination": "hawaii",
        "destination_fullname": "Hawaii",
        "transport_method": "red convertible",
        "requested_sightseeing_stops": "glass-bottom boat tour of marine life and coral reefs and whales",
        "tour_guide": None,
        "season": "late spring",
        "art_style": "tapa",
    },
    "iceland": {
        "destination": "iceland",
        "destination_fullname": "Iceland",
        "transport_method": "rental car",
        "requested_sightseeing_stops": "ferry boat ride",
        "tour_guide": None,
        "season": "summer (with long daylight hours)",
        "art_style": "icelandic-illuminated",
    },
    "montreal": {
        "destination": "montreal",
        "destination_fullname": "Montreal, Quebec",
        "transport_method": "",
        "requested_sightseeing_stops": "Osheaga Music and Arts Festival in Parc Jean-Drapeau",
        "tour_guide": "bilingual (French and English) college student majoring in history and specializing in the history of Quebec",
        "season": "summer",
        "art_style": "quebecois",
    },
    "losangeles": {
        "destination": "losangeles",
        "destination_fullname": "Los Angeles, California",
        "transport_method": "",
        "requested_sightseeing_stops": "Griffith Park (including the Hollywood sign), Santa Monica beach boardwalk, Mount Wilson Observatory",
        "tour_guide": None,
        "season": "summer",
        "art_style": "graffiti",
    },
    "normandy": {
        "destination": "normandy",
        "destination_fullname": "Normandy, France",
        "transport_method": "train",
        "requested_sightseeing_stops": "Normandy Impressionist Festival",
        "tour_guide": None,
        "season": "summer",
        "art_style": "fauvism",
    },
    "amsterdam": {
        "destination": "amsterdam",
        "destination_fullname": "Amsterdam, the Netherlands",
        "transport_method": "bicycle tour",
        "requested_sightseeing_stops": None,
        "tour_guide": None,
        "season": "late spring",
        "art_style": "van-gogh",
    },
    "puertorico": {
        "destination": "puertorico",
        "destination_fullname": "Puerto Rico",
        "transport_method": "car",
        "requested_sightseeing_stops": None,
        "tour_guide": None,
        "season": "summer",
        "art_style": "carribean-folk",
    },
    "patagonia": {
        "destination": "patagonia",
        "destination_fullname": "Patagonia",
        "transport_method": "bus and ferry boat",
        "requested_sightseeing_stops": None,
        "tour_guide": None,
        "season": "winter",
        "art_style": "peruvian",
    },
    "prague": {
        "destination": "prague",
        "destination_fullname": "Prague, Czech Republic",
        "transport_method": "walking tour",
        "requested_sightseeing_stops": None,
        "tour_guide": None,
        "season": "autumn",
        "art_style": "oil",
    },
    "mumbai": {
        "destination": "mumbai",
        "destination_fullname": "Mumbai, India",
        "transport_method": "rickshaw",
        "requested_sightseeing_stops": None,
        "tour_guide": None,
        "season": "springtime",
        "art_style": "mughal",
    },
    "goa": {
        "destination": "goa",
        "destination_fullname": "Goa, India",
        "transport_method": "motor scooter",
        "requested_sightseeing_stops": None,
        "tour_guide": None,
        "season": "summer",
        "art_style": "tanjore",
    },
    "yellowstone": {
        "destination": "yellowstone",
        "destination_fullname": "Yellowstone National Park",
        "transport_method": "hybrid bicycle (for roads and trails)",
        "requested_sightseeing_stops": None,
        "tour_guide": None,
        "season": "summer",
        "art_style": "american-romanticism",
    },
    "rome": {
        "destination": "rome",
        "destination_fullname": "Rome, Italy",
        "transport_method": "Vespa scooter",
        "requested_sightseeing_stops": "the Roman Forum, the Colosseum",
        "tour_guide": None,
        "season": "summer",
        "art_style": "baroque",
    },
    "marrakech": {
        "destination": "marrakech",
        "destination_fullname": "Marrakech, Morocco",
        "transport_method": "private car",
        "requested_sightseeing_stops": None,
        "tour_guide": "driver who speaks five languages fluently",
        "season": "summer",
        "art_style": "moroccan",
    },
    "accra": {
        "destination": "accra",
        "destination_fullname": "Accra, Ghana",
        "transport_method": "tro-tro (minibus)",
        "requested_sightseeing_stops": None,
        "tour_guide": None,
        "season": "late spring",
        "art_style": "ghanaian",
    },
    "addisababa": {
        "destination": "addisababa",
        "destination_fullname": "Addis Ababa, Ethiopia",
        "transport_method": "bajaj (a little three-wheeled car that's perfect for sightseeing)",
        "requested_sightseeing_stops": None,
        "tour_guide": None,
        "season": "early spring",
        "art_style": "ethiopian",
    },
    "madagascar": {
        "destination": "madagascar",
        "destination_fullname": "Madagascar",
        "transport_method": "private taxi (and a ferry to get between islands)",
        "requested_sightseeing_stops": "baobab trees (as made famous by 'The Little Prince')",
        "tour_guide": None,
        "season": "autumn",
        "art_style": "watercolor",
    },
    "seoul": {
        "destination": "seoul",
        "destination_fullname": "Seoul, South Korea",
        "transport_method": "Seoul metro subway",
        "requested_sightseeing_stops": None,
        "tour_guide": "an enthusiastic older gentleman",
        "season": "summer",
        "art_style": "minhwa",
    },
    "beijing": {
        "destination": "beijing",
        "destination_fullname": "Beijing, China",
        "transport_method": "private car",
        "requested_sightseeing_stops": "Chinese New Year's celebration and parades throughout the streets",
        "tour_guide": "our driver, a woman who is overflowing with interesting historical tidbits",
        "season": "winter",
        "art_style": "chinese-silk",
    },
    "vancouver": {
        "destination": "vancouver",
        "destination_fullname": "Vancouver, British Columbia",
        "transport_method": "bus and aquabus",
        "requested_sightseeing_stops": None,
        "tour_guide": None,
        "season": "summer",
        "art_style": "retrofuturism",
    },
    "norway": {
        "destination": "norway",
        "destination_fullname": "Norway",
        "transport_method": "train and ferry along the fjords",
        "requested_sightseeing_stops": "Nordfjordeid, and also a hike in the mountains about the fjords",
        "tour_guide": None,
        "season": "a temperate summer with long days of gentle sunlight",
        "art_style": "viking-engraving",
    },
    "dubrovnik": {
        "destination": "dubrovnik",
        "destination_fullname": "Dubrovnik, Croatia",
        "transport_method": "bicycle",
        "requested_sightseeing_stops": None,
        "tour_guide": None,
        "season": "late summer",
        "art_style": "pointillism",
    },
}