// this code is generated from the story file queenstown_2023-11-10_23-15-53.txt
    // min_stops is set to 1

    package com.downdogapp.cue

    object SleepStoryTravelShortQueenstownCues : SleepStoryPoseCues {

    override val start =
    "Today, we embark upon a soothing journey to Queenstown, New Zealand, amid the warmth and vibrancy of summer. Nestled on the shores of crystal-clear Lake Wakatipu, the town is situated against an incredibly picturesque background, with the majestic Remarkables mountain range cutting an imposing figure in the distance. The soft murmur of the lake's gently lapping waves, combined with the dappled sunlight filtering through the verdant trees, creates an absolutely peaceful and tranquil atmosphere. Our mode of exploration is as unique as our destination: water taxis. These quaint vessels, moving smoothly on the tranquil waters, promise a unique perspective on the beautiful landscapes we are about to encounter. The anticipation of ornate vistas and serene waterways provides an air of gentle excitement to the start of our adventure, like the first brushstroke on a painter's canvas. Now, let's begin our sightseeing journey, starting with the breathtaking Milford Sound." /
"As our water taxi glides into Milford Sound, we're instantly in awe of the majestic fjord, carved masterfully by glaciers during the ice ages. So striking is its beauty that author Rudyard Kipling fittingly described it as the eighth wonder of the world. Stretching 15 kilometers inland from the Tasman Sea, the fjord is a powerful testament to the artistry of nature. Rock faces tower 1,200 meters or more on either side, standing tall like ancient sentinels. We catch our breath at the sight of the Elephant peak, its figure reminiscent of an elephant's head and standing at a height of 1,517 meters. Not far off is The Lion, a crouching figure standing 1,302 meters high." /
"The calm waters mirror the towering cliffs and waterfalls in a spectacular display, while marine life adds dynamism to the serene landscape. Dolphins leap playfully in our wake, seals bask in the sun on rocky shores, and if we're lucky, we might even spot the rare Fiordland Crested Penguin waddling along the shoreline. As we take in these sights, a delicious aroma wafts from the galley below." /
"Time seems to lose its significance in this enchanting place. Before long, we find ourselves dining on fresh Fiordland's crayfish, a local delicacy perfectly complemented by the breathtaking view. Afterward, we retreat to the deck, indulging in the gentle rocking of the boat and the cool breeze stroking our faces. The ethereal beauty of the cascading waterfalls, vast cliff faces, and tranquil forests enrapture us. Every turn reveals new, wonderful sights, infusing an undulating sense of wonder in our hearts. Simple moments like these—basking in nature's unassuming elegance—are what make our journey truly extraordinary. We set off again, ready to uncover the next wonders that Queenstown holds for us." /
"Our nautical journey continues with a soothing glide towards the Queenstown Gardens. As elegantly manicured as they are naturally enchanting, the gardens sprawl across a small peninsula that juts into tranquil Lake Wakatipu, offering breathtaking panoramic views. The historical significance of these gardens, officially opened by Sir John McKenzie in 1867, is beautifully juxtaposed against a backdrop of towering mountains and the peaceful lake." /
"The Queenstown Gardens are a veritable Eden, teeming with both native and international flora. Each plant and tree flourishes under the careful hands of committed gardeners, blooming proudly in the warm summer sunlight. As we drift along the lake's serene waters, we catch sight of visitors leisurely exploring the gardens. They amble along the well-tread paths, picnicking, and playing games of frisbee golf, their laughter and enjoyment blending harmoniously with the gentle bird songs." /
"We can almost taste the deliciously cool and sweet gelato from Patagonia Chocolates, just as those strolling around the gardens do, their hands clasping dripping cones as they peruse flowerbeds and curling vines. Perhaps it is this scene that inspired the rich emerald descriptions in Margaret Pemberton's novel 'A Season of Secrets'. We reaffirm our love for Queenstown's quaint charm, promising to set foot in this beautiful sanctuary once we make landfall." /
"As we pull away, our water taxi steers towards Mt. Nicholas High Country Farm, an emblem of New Zealand's vibrant rural life. For over 150 years, this family-run farm has thrived in the shadow of its mountainous namesake. Across the water, the view offers a sweeping panorama. Tens of thousands of Merino sheep, one of the world's oldest and most resilient breeds, gently dot the landscape as does a variety of other chirpy farm animals." /
"Visitors in far-off fields can be seen engrossed in wool spinning, their fingers deftly twisting the soft strands into threads of authenticity. Others are enjoying first-hand encounters with the pigs and chickens, their wide smiles, and animated gestures a testament to the joy of connecting with life on the farm. A whiff of delectable roasts on the air telegraphs a typical dining experience here: a traditional farm BBQ, showcasing locally sourced lamb cooked to perfection, imbued with aromatic seasonings that spark our hunger with anticipation." /
"On this peaceful journey across Lake Wakatipu, our hearts flutter like the wings of the native birds dotting the open skies. The hum of our water taxi engine, a pleasant counterpoint to the natural serenade of gently lapping water and far-off animal calls, lends rhythm to our anticipation for the authentic farm-life experience that awaits. But for now, we allow the alpine landscapes and the lovely water views to wash over us, sinking deeper into the soothing ambiance of this idyllic Queenstown tour."

    override val middle = listOf(
    "Our water taxi gently pulls away from the shores of Mt. Nicholas High Country Farm, tracing a path of delicate ripples across Lake Wakatipu towards the renowned Peregrine Winery. Nestled amidst plush greenery and in the shadowy embrace of the rugged mountains, the winery, established in 1998, is a beacon of fine wine culture in the Central Otago region." /
"As our boat leisurely cruises, we spot the silhouette of Peregrine Winery, its architecture an award-winning masterpiece that seamlessly merges with the breathtaking panorama. Named after the native Peregrine falcon, this venue invites us with the promise of sophisticated wine tasting experiences. We find ourselves eagerly picturing sampling their celebrated Pinot Noir, accompanied by locally sourced cheeses, all with a backdrop of rolling vineyard landscapes." /
"As our water taxi pirouettes playfully around in the lake, a small group of ducks cuts a dynamic path in the waters, seemingly escorting us to our destination. Their playful course presents a charming spectacle against the lush vineyards growing ever closer. The thought of enjoying the final product of these vine-filled vistas, after a patient maturing period, fills us with anticipatory delight. Though the winery will necessitate a short overland journey after we disembark, the prospect only adds to the unfolding experience." /
"An enchanting hum signals the start of our onward journey to Queenstown Hill. Also known as Te Tapu-nui, the 'mountain of intense sacredness,' Queenstown Hill promises panoramic vistas worth every step of the hike. A sense of reverence seems to murmur in the wind as we note the significance of this locale, steeped both in Maori and colonial history." /
"We daydream about the 'Time Walk', where plaques dot the trail, offering insights into the region's gold-mining past and its heritage. We also envision the iconic 'Basket of Dreams' sculpture - an emblem of Queenstown Hill - and dwell on the communal moments spent here - picnics, shared laughter, and frame-worthy pictures etching perfect memories against nature's grand canvas." /
"Later, nursing a traditional Kiwi meat pie accompanied by a local craft beer in a quaint café after the descent doesn't seem too far off a reality. But, for now, we relish the onset of the hill adventure as our water taxi docks. Amidst friendly nods from our fellow tourists, we step ashore, our hearts filled with calm anticipation as our Queenstown Hill exploration begins.",

"Resuming our journey, we gently steer the water taxi away from Queenstown Hill and meander towards our next fascinating destination, Walter Peak High Country Farm. This traditional New Zealand farm, steeped in rich history since 1860, teems with endearing Scottish highland cows, red deer, and a flock of fluff-laden sheep, reminiscent of the station’s first herd introduced by Von Tunzelmann and MacKellar. The tranquility of the open waters of Lake Wakatipu provides a serene passage to this traditional farm." /
"As we approach the farm, the sight of wagging tails and frisky, gamboling lambs on the shoreline warms our hearts. Upon docking, a flock of friendly ducks engages in a playful ballet around the water taxi, their joyous quacks a tuneful welcome. The rustic charm of the farm activities beckons us alluringly. Imagine witnessing the herding prowess of working sheep dogs, shearing the thick wool from cooperative sheep, and later, spinning that very wool into soft, warm yarn. The opportunity to hand-feed the amiable Rumble, the resident Scottish highland cow, adds an incredible note of camaraderie to this truly immersive farm experience." /
"The highlight remains the traditional BBQ lunch, served in the colonial-style dining room. We can almost taste the succulent local lamb, venison, and seafood, visualizing their mouthwatering arrangement on our plates enhanced by fine New Zealand wine or beer. The delightful promise of dessert teases our appetite, completing the prospect of a hearty farm meal that we look forward to." /
"Leaving the farm, we direct our course towards the historic and scenic gorge of Skipper’s Canyon. En route, we listen to the soft whispers of the Shotover River as it serenely courses through the landscape. A river once proclaimed during the gold rush as the 'richest river in the world', it now offers tranquil beauty that seems timelessly captured in its sparkling waters. The breathtaking panoramas of the canyon around us recall picturesque scenes from the 'Lord of the Rings' trilogy, the embodiment of the fantasy landscape of Middle Earth." /
"The treacherous Skippers Canyon Road, frighteningly narrow and etched along a cliff face, narrates countless stories of the region's bygone gold-rush era. We let our imagination run free as we try to picture gold panning in the river, sifting the cool, clear waters through our fingers in hopes of catching a glisten of that precious metal. This experience, a delightful blend of adventure and tranquility, paints our journey with strokes of history, excitement, and serene pleasure. With the promise of more exploration ahead, our water taxi persists through the soothing waters, leading us onward for more discoveries on this unforgettable tour.",

"Trading the rugged landscapes of Skipper’s Canyon behind, our water taxi peacefully charts its course towards the dreamy settlement of Glenorchy. This small town unfurls at the northern end of Lake Wakatipu, its landscape an undulating tapestry of majestic mountains, serene lakes, and lush greenery—a sight so wondrous it was immortalized in the celluloid pages of The Lord of The Rings and The Hobbit trilogies." /
"As our water taxi and its delightful wake draw closer, Glenorchy performs a brilliant play of colors, its verdant foliage standing in stark contrast with the shimmering blue of the lake. A collective gasp slips from us all when we learn it is the gateway to 'Paradise'—a place of such heart-wrenching beauty it mirrors the heavenly abode itself. It’s not just the nature that mesmerizes us, though. The town carries an unmistakable scent of its colonial past, having been a Scheelite mining base in the late 1800s." /
"Pulling into the shore, we vividly imagine savoring a slice of New Zealand in the form of a hearty venison pie, a local delicacy easily found in the welcoming cafes here. We also visually follow the adventurers setting out for the Routeburn Track, one of New Zealand's Great Walks, their enthusiasm washing over us. But equally riveting is the prospect of smoothly cruising back on our water taxi, seats soaked in the afternoon sun, winds whispering tales of charismatic locales, and the thought of the upcoming visit to Arrowtown teasing our anticipation." /
"Arrowtown, a historic gold mining town in the Otago region, comes into view. A testament to the Otago gold rush, the town, with its quaint shops and eateries, paints a captivating picture. The miners' cottages, their original architecture preserved, peek through the town's corners, offering glimpses into its vibrant past. Deep history blends subtly with Hollywood fame as we remember scenes from Peter Jackson's 'The Lord of the Rings' trilogy, filmed amidst this very old-world charm." /
"Stepping off the water taxi, we feel a tug to the past. The vision of the well-preserved cottages against the backdrop of the Arrow River gives us vivid senses of the town's past. The promise of gold still echoes off the preserved miners' homes, inciting us to picture the lives of Chinese immigrants who once flocked here in search of gold. The notion of ending our day with a heavenly meat pie from the Arrowtown Bakery or the regal sip of pinot noir from the Central Otago wine region sums up an adventure of pleasing contrasts and gentle excitement. Yet, as we gaze upon the picturesque backdrop, we know our exploration isn't over; the water taxi trip holds more treasures waiting to be discovered in this wondrous journey."
    )

    override val end =
    "Resuming our tranquil waterborne journey from the historic allure of Arrowtown, we navigate our water taxi towards the breathtaking Lake Hayes. Affectionately known as the 'mirror lake', it is famous for flawlessly reflecting the towering mountains that cradle its clear waters. As our water taxi skims across its surface, history whispers of Maori fishermen and the cultivation of potatoes along the fertile shores." /
"On this occasion, Lake Hayes lives up to its reputation – the water mirrors not only the surrounding mountains but also the cloud-kissed sky. We think of the Lake Hayes Loop, a cherished trail that has been immortalized in The Lord of the Rings, now being explored by walkers, runners, and cyclists. A longing seizes us to join them and feel the earth beneath our feet while we trace the edge of the lake." /
"To savor the beauty from the shore, we imagine spreading out a picnic with delectable kiwi lamb, perfectly paired with local wines from the nearby Gibbston Valley wineries. Let us not forget our fellow visitors we glimpse through the boat's windows, engaged in a silent dance with nature as they attempt fly fishing, their reflections shimmering on the water's surface. The Billy Joel lines “A mirror of its time,” seems to manifest beautifully, as we share a warm moment with our captain, reveling in a group of majestic black swans performing a synchronised ballet on the mirror-like lake." /
"The journey continues to combine tranquillity with gentle excitement, our next stop - Bob’s Cove Nature Walk. From Lake Hayes, our water taxi gently steers towards the verdant invitation of Bob's Cove. Serenity permeates the air as we cruise towards the age-old walking track, the Bridle Path, which once under the footfall of the Maori now contemplates ours." /
"The native bush canopy, laced with bird songs and fluttery acquaintances like bellbirds and native wood pigeons, bids us a warm welcome. Lending an exotic touch are introduced species like quails, which gingerly explore the native habitat. A high point in our journey unfolds as we spot the cove itself, an historic reserve since 1975. Here, a perfectly preserved page of natural beauty awaits us." /
"While the promise of a leisurely nature walk fills us with anticipation, we take a moment to drink in the sight of the cove from our water taxi—an untouched canvas of swaying trees reflecting in the lake's clear surface. It's an idyllic union of fresh-water spray and the hidden treasures of the Bob's Cove Nature Walk, a memory in the making that promises more encounters with the mesmerising charm of Queenstown." /
"Carrying with us a bouquet of unforgettable experiences, we journey onwards, ready to paint the final strokes on our travel canvas. Our trusty water taxi eases onward, charting a course that reflects the iridescent hues of the setting sun on Lake Wakatipu. Pure excitement kindles in our hearts as we approach the acclaimed Amisfield Winery." /
"Founded in 1988, the Amisfield Winery holds an esteemed position in the pantheon of extraordinary cool-climate wines. Tucked cosily in the Pisa sub-region of Central Otago, the sprawling 200-hectare vineyard is a haven for grape harvesting. Among the many decorated wines it produces, the Amisfield Pinot Noir stands as a shining symbol of its excellence, even bagging the prestigious 'Best New Zealand Wine' award at the International Wine Challenge in London." /
"As we disembark, the soft snick of wine corks echoes around us like a medley of welcoming chimes, inviting us to celebrate the art of winemaking. Our palates invigorated by the anticipation of tasting their award-winning Pinot Noir, we let the delicate, earthy notes tease a melody on our tastebuds. Parallely, the famed 'Trust the Chef' menu from the vineyard's celebrated Bistro tempts us with an array of mouthwatering dishes, each an ode to local, fresh ingredients and artisanal methods." /
"We imagine allowing ourselves the simple pleasure of unbeknownst dishes paired perfectly with their wines, a sumptuous rendezvous of food and drink. The winery provides a chance for us to stroll leisurely through sun-dappled vines, breathing in the aroma of growing grapes, and gaining insight into the intricate processes of winemaking. This immersion into viticulture is both enlightening and enchanting, elucidating the journey of grape to glass." /
"As the day ages beautifully into twilight, we trace our steps back to the water taxi, a reflection of our own journey bathed in the remaining warm hues of the day. On the tranquil ride back, we cradle a glass of the vineyard's star nectar, the Pinot Noir. Nestled in the comfort of our lightly rocking vessel, the cool lake breeze becomes our companion. We observe nature's grand theatre performing its masterpiece – a stunning Queenstown sunset." /
"Rust-orange light brushes the mountains, playing subtly along the orchestra of waves on Lake Wakatipu. Such entrancing beauty perfectly pours into the final chapters of our Queenstown excursion. As we approach the end of this peaceful voyage, our hearts brim with memories and stories woven with each stop we made—the towns, landscapes, the shared smiles, the mirrored lakes, the culinary delights. All these elements dance together to create a symphony, leaving an indelible mark on our hearts. This journey is proof that life's most beautiful gifts unfold as we linger along the quieter pathways of adventure, ensuring Queenstown, New Zealand, lives on within us, a gentle echo that whispers, 'One day, we shall meet again.'"
    }