// this code is generated from the story file newyorkcity_2023-11-10_23-15-53.txt
    // min_stops is set to 1

    package com.downdogapp.cue

    object SleepStoryTravelShortNewyorkcityCues : SleepStoryPoseCues {

    override val start =
    "The smoky scent of roasted chestnuts fills the air as our open-top bus tour rolls into the heart of New York, New York. Autumn leaves paint the city streets in hues of gold and emerald, as a crisp wind sing-songs its way through the concrete jungle. It’s a slice of magic tucked into the bustling metropolis, a season that wraps the city in a calmness that brings out all of its vibrant beauty. Our guide, a jovial man with a thick Brooklyn accent, informs us that his family has been rooted in New York City for many generations. His words burst with passion for the city, offering a sense of familiarity and endearing authenticity to our tour. There is an absolute hum of eagerness amongst us as we anticipate the wonders and secrets the city is about to reveal. With a gentle start on the bus, a route through the Metro, and some strolls along the way, we are ready to embark on our sightseeing journey." /
"Our first stop is a verdant oasis amidst towering skyscrapers, Central Park. Opened in 1857, this green lung of the city spans an impressive 843 acres. Central Park is a character in its own right in numerous books, movies, and TV shows, a rendezvous point for heartwarming scenes, dramatic revelations, and soulful reflections. You can almost hear the whispers of, “Don’t sing. It’s okay, you know. Let’s just walk. Can we do that?” from the movie 'Enchanted' echoing in the cool breeze. The park's large Lake beckons, its calm surface begging to be disturbed by the oars of one of the rental rowboats from the Loeb Boathouse." /
"New Yorkers from all walks of life occupy the park making the most of the peaceful environment: there are joggers pacing themselves along the winding paths, families playing catch on the vast green expanses, and couples lounging under dappled sunlight breaking through the canopy of rustling autumn leaves. As we perch on leather seats on the upper deck of our open-top bus, or find ourselves peering out from the subway, feast your eyes on the dance of life below you, soaked in joyous sunlight." /
"The city's humble culinary delicacies call out to the bold. At a nearby cart, a vendor grills hotdogs that pair perfectly with a classic soft pretzel. Moreover, for those seeking a formal dining experience, both Tavern on the Green or The Loeb Boathouse offer savory bites paired with pleasing park views. The symphony of ambient sounds, delicious tastes, and visual beauty that Central Park offers is an overwhelming experience of delight and awe – but this is only the beginning of our journey. As our guide fondly recounts stories of his family's history entwined with the park's history, we can't wait to see what's next." /
"As our tour continues, our eyes land on the regal façade of the New York Public Library. Since its inauguration in 1911, this imposing architectural marvel has been a cornerstone of scholarship and literature in the city. Guarding its gateway, the iconic lion statues, 'Patience' and 'Fortitude', gaze at us with stoic charm, silently inviting us to step into the world of knowledge that lies within." /
"Every corner of the library whispers legends. It's as if echoes of famous movie scenes shot here, from 'Ghostbusters' to 'Sex and the City', rebound in the hushed silence. Beneath grand chandeliers, nearly 53 million items rest on the library's shelves, each one a beacon of enlightenment that draws intellectuals from far and wide. The reading room sprawls out, an expanse of quietude, accommodating up to 500 readers who find themselves cocooned in historical grandeur, engrossed in a ballet of ideas woven through the page. There's a palpable excitement as faces lit by the soft light bend over their chosen books." /
"Nestled inside the Stephen A. Schwarzman Building, 'Amy's Bread Cafe' offers respite to visitors, with the tantalizing fragrance of coffee wafting alongside the aroma of freshly baked goods. As we depart, we might exchange a few words with our guide, gaining insights into the library's historic tales flavored with his vibrant Brooklyn accent. A perfect memento could be a family photo taken with the stoic lion statues at the front, bookmarking our visit to this grandeur." /
"A shift of landscape awaits us as we move toward Chelsea Market. Constructed on historic grounds where the iconic Oreo cookie first emerged in 1912, this gastronomic haven occupies an entire city block, one steeped in culinary delights. Our senses are immediately entrapped by savory aromas of the vast array of food from all corners of the world. The spirit of New York food culture radiates through every vendor, from the warm, gooey brownies of 'Fat Witch Bakery' to the fresh catch at 'Lobster Place'." /
"The clatter of pots, the buzz of lively conversation and the vibrant energy of the crowd bring the building to life. It's a symphony of sights, sounds, and tastes, a confluence of old and new. A peak inside shops reveal gourmet groceries, an array of premium wines, or a visitor lost in the delicacies of a food stall. Every bite, every sound, and every sight in this bustling market resonates with a narrative of the city's culinary history. As we stroll down the bustling corridor, our guide's enthusiastic voice echoes amid the hum of activity, spinning historic tales of the former biscuit factory, imbued with the peculiar allure of his Brooklyn accent. Our tour takes a delicious turn, indulging our taste buds while simultaneously enriching our understanding of this iconic city locale."

    override val middle = listOf(
    "With the taste of our culinary explorations in Chelsea Market still lingering, our sightseeing tour draws us back to the realm of art. The Metropolitan Museum of Art, or the Met as it's affectionately known, awaits us next. This iconic institution wasn't always the grand establishment it is today. Since its modest inception in 1870, it has grown into one of the largest and most comprehensive art museums in the world." /
"The moment we step into the palatial structure, the air seems to hum with over 5,000 years of human creativity. Two million masterpieces adorned in gilded golden frames beckon us in, each one whispering tales from distant lands and times. We find ourselves enveloped in an art lover's paradise, where one moment we might be marveling at the regality of Washington crossing the Delaware, the next immersing ourselves in the captivating mystery of Madame X." /
"Even outside of the galleries, this grand dame of art museums continues to charm. The Roof Garden Cafe invites us to savor a refreshing pause. Perched high above the city, it cradles a panoramic view of Central Park that stretches into the horizon. Amid neatly curate flowerbeds, an array of freshly prepared culinary delicacies tantalize our senses." /
"The call of our tour awaits, and adding to our experience, our vibrant Brooklyn-voiced guide breathes life into every room and exhibit. His enlightening commentary adds layers of color, context, and local flavor, helping us navigate the rich tapestry of art history that adorns the walls. Together, we take in the sunlight streaming through the glass on the Temple of Dendur or the carefully crafted suits in the Armor Gallery." /
"Leaving a marvelous art scene, our path starts intertwining with the threads of history. Nestled on the southern tip of Manhattan Island, Battery Park offers a refreshing interlude. Named after the artillery batteries that once protected the harbor in the city's early years, it's now an urban sanctuary where history, natural beauty, and modern city life converge." /
"Resting our eyes on the gentle lapping waves, we marvel at the iconic silhouette of the Statue of Liberty. She stands tall on Liberty Island, holding her torch aloft, emblematic of the freedom and diversity that New York represents. The metallic sculpture of The Sphere glistens in the autumn light, a reminder of resilience and unity salvaged from the rubble of the Twin Towers." /
"As we stroll along the winding paths, sampling local delicacies of oysters or clam chowder from nearby seafood restaurants, our guide shares poignant stories of how more than four million immigrants passed through Castle Garden, located within the park, before Ellis Island even opened in 1892. His family history woven into this narrative transforms the facts into a deeply personal commentary that instills an emotional connection with the history of this magnificent city. The intertwining of our current explorations with his familial ties brings an intensity to our visit, forging an unforgettable bond with New York.",

"Our next destination, the Museum of Modern Art or MoMA, is a beacon of New York's vibrant art scene. Founded in 1929, MoMA is a pioneer in its league, the first of its kind to curate an astonishing repository of modern and contemporary art in America. As soon as we cross the threshold, the pulse of creativity hums along the museum galleries." /
"The treasures within these walls leave an indelible impression; Van Gogh's 'Starry Night', exploding with emotional turbulence, Picasso's groundbreaking 'Les Demoiselles d'Avignon', and the genius of Dali, Kahlo, Warhol, and more, each waiting for us to discover their unique narratives. As we weave through the museum, every artwork unravels a thread of stories, controversies, reflections, and revolutions, breathing life into the silent canvases and installations." /
"Our guide, his Brooklyn accent filling the spacious halls, infuses each description with passion and authenticity. As we stop in front of Van Gogh’s ‘Starry Night’, he weaves a vivid tale of the artist's chaotic mind, etched into the swirls of the painted night sky, created from the confines of a mental asylum. Further exploration leads us to 'The Modern', the MoMA's Michelin-starred restaurant. Nestled amidst art, the restaurant serves dishes as intriguing as the surrounding exhibits, each plate a curated experience crafted from fresh, seasonal ingredients." /
"Leaving the artistic cocoon of MoMA, the cityscape transforms, bringing us into the vibrant heart of Chinatown. Steeped in cultural richness, time seems to take a delightful turn, merging modern life seamlessly with traditional heritage. Established in the mid nineteenth century by Cantonese immigrants, this bustling neighborhood is now home to one of the densest Chinese populations in the Western Hemisphere." /
"Our guide's engaging narration surrounds us as we navigate the intricate labyrinth of streets. From the open-top bus, we catch glimmers of locals shopping for oriental groceries, haggling over prices, or savoring authentic Chinese dishes. Delectable aromas of delectable Dim Sum, Peking Duck, and Wonton Soup waft from countless eateries, tantalizing our taste buds. A memorable part of the immersion in this Asian enclave is disembarking the Metro at Canal Street station, stepping straight into a dynamic blend of culinary scents, colorful storefronts, and the melodic chatter of Mandarin and Cantonese intermingling with the fall air. That's the beauty of a tour around Chinatown, a delightful cultural mélange, a slice of Asia in the heart of New York City.",

"As we continue our tour, the distinctive silhouette of the Solomon R. Guggenheim Museum emerges. Breaking the monotony of the city's rectangular structures, this architectural marvel designed by Frank Lloyd Wright dares to spiral upwards like a radiant seashell towards the sky. Watching the ivory edifice unfurl against a backdrop of high-rise buildings evokes whimsical echoes of Ayn Rand's 'The Fountainhead' in our minds, an ode to human imagination and architectural prowess." /
"Sixteen years, 700 sketches, and six sets of working drawings — that's the meticulous planning that went into this unique design. Conceived as a 'temple of spirit,' the museum is a testament to Solomon R. Guggenheim's growing passion for art, a feeling easily contagious as we explore its extensive collection of modern and contemporary art." /
"The dynamic creativity within the museum extends beyond its expressive artworks. At the Wright Restaurant, culinary artistry comes to life, conjuring a memorable dining experience influenced by the flavors and ingredients of the season. As we visit, we find visitors clicking photographs, sketching the interiors, and immersing themselves in the mesmerizing world of contemporary art. With our guide's thick Brooklyn accent offering lively commentary, we can't help but imagine the stories behind each masterpiece, enriching our journey through this spiraling wonder." /
"Departing from the quiet introspection of the museum, our open-top bus tour takes us next to Greenwich Village. This neighborhood, known for its bohemian charm, guilelessly invites us to surrender to its laid-back rhythm. Since the late 19th century, the Village has been an enclave for artists, writers, and dreamers, its cache of stories seamlessly blending into the city's cultural tapestry." /
"The heart of this neighborhood beats with the rhythm of Washington Square Park, a symbol of the Village's diverse spirit. Originally a burial ground for the unknown, the park now unfolds into a panorama of spectacle and amplitude. Here, people stroll with dogs, engage in spirited street performances, and lose themselves in leisurely coffees at the myriad streetside cafes dotting the streets." /
"Our guide, his warm Brooklyn accent enlivening the narrative, amplifies the neighborhood's illustrious history. He paints a vivid picture of the spirited Stonewall Riots, immortalizing the fight and spirit of the LGBTQ+ community, and recites tales of literary giants like Edgar Allan Poe, who composed his famed “The Raven” within these storied dwellings." /
"Savoring a delectable plate of Italian pasta at a local bistro or relishing the creamy textures of fresh mozzarella, we experience the Village's culinary prowess. The vibrancy of Greenwich Village - its charm, tales, and flavors - leaves an indelible print, further enriching our immersive journey through the city that never sleeps, New York, New York."
    )

    override val end =
    "Our tour's next stop is the Flatiron District, an area teeming with historic charm and an unmistakable aura of sophistication. The namesake of the district, the illustrious Flatiron Building, stands resolute at the intersection of Broadway, Fifth Avenue, and 23rd Street. This architectural gem was one of the early 20th century's first skyscrapers, its unique triangular shape an enduring symbol of New York's inventive spirit, greeting us like an old friend from the pages of the Amazing Spider-Man comic series." /
"The district proudly flaunts architectural treasures like the MetLife Tower, a former holder of the 'tallest building' title that reaches upward, silently narrating tales of a time when it outranked all others in stature. As we delve deeper into the neighborhood, our guide's Brooklyn accent reverberates through the cool air, enriching our journey with stories about the district's architectural accomplishments and its vibrant history." /
"Summer afternoons here are a tapestry of flavors and sights. The mouth-watering aroma of juicy ShackBurgers wafting from the beloved Shake Shack in Madison Square Park entices both locals and tourists alike. The Flatiron Plaza teems with life, a melting pot where the city's residents bask in the sun, engage in chess matches, or savor a cup of coffee from one of the many surrounding cafes." /
"Drawing away from the bustling city, our tour now transports us to a haven of tranquility nestled in the heart of Brooklyn, the Brooklyn Botanic Garden. Opened in 1910, this urban sanctuary intertwines the allure of nature with the importance of conservation. The sprawling garden is a vibrant canvas, boasting a riot of colors and scents, from the spectacular Cherry Blossom Festival to the diverse array of roses in the renowned Cranford Rose Garden." /
"An artistic rendition of a serene Japanese landscape manifests in the first Japanese garden to be fashioned in an American public garden, the Japanese Hill-and-Pond Garden. We spot artists capturing the beauty of the lush surroundings in delicate brush strokes, and the bright laughter of children reverberates through the Discovery Garden's interactive exhibits." /
"Amidst the sensory serenade, we pause our exploration to enjoy snippets of refreshment at the Yellow Magnolia Café. Overlooking the Lily Pool Terrace, it offers locally sourced, seasonal fare that perfectly complements our immersive botanical adventure." /
"Our guide, a native New Yorker, continues to weave the intricate tapestry of his family history along with the city's own, their narratives coalescing magically to form a vibrant canvas enriched by passion, personal anecdotes, and undeniable Brooklyn charm. The transition from the city's architectural marvels to its serene green expanses cements the city's beautifully harmonious blend of bustling energy and tranquil redemption." /
"Our adventure in the city of New York has been a vibrant kaleidoscope of art, history, diverse cultures, and unique flavors. We've soaked up the voices, sounds, and colors of the city, each experience painting a brushstroke upon our travel canvas. As our journey begins to wind down, one last gem awaits our exploration – a modern testament to creative urban redesign and the persistent spirit of the city: the High Line." /
"Like a green tendril winding its way through the concrete heart of the city, the High Line was a former freight rail line transformed into a haven of tranquility. An ambitious project inspired by Paris's 'Promenade Plantée,' it is now an elevated park extending 1.45 miles that breathes life into a once obsolete rail line. Architects and designers collaborated to repurpose this piece of history, blending the rigid linearity of the old rail tracks with the meandering grace of meticulous landscaping." /
"What makes the High Line stand out in our journey, aside from its ingenious concept, is the new perspective it offers. As we ascend the steps, we find ourselves encased in an urban canyon. The New York skyline extends vertically, the surrounding buildings towering alongside the park as if leaning in to appreciate the view. Iconic artworks are a highlight here, like the black and white image of a young man by French artist JR; he mirrors our poised excitement, ready to step beyond the line and immerse into the charming beauty of this place." /
"At this height, the busy city below seems to hush, its vibrant rhythm resonating like a distant melody. We glimpse life along the High Line - tourists capturing memories against the stunning backdrop, artists sketching landscapes, and locals sharing laughs. A refreshing breeze from the river teases the vegetation, as the linear park snakes its course, offering us breathtaking views of the architectural marvels and the calming Hudson River." /
"Food also finds its way here - a testament to New York's culinary scene. From Chelsea Market's diverse fare nearby to the in-park eateries, the High Line presents tempting delights. A refreshing popsicle on a sunny afternoon, a warm cup of coffee paired with the city's views, or a luxurious Italian dinner under the stars, food experiences intermingle with our exploration." /
"Our Brooklyn-accented guide animatedly shares tales of the High Line's evolution, its industrial past cinematic in his narration. New stories echo off the steel, blend with the fauna, and ripple across the Hudson, knitting past, present, and future together." /
"Our eyes have feasted on art, our palate on flavors, our ears on stories, and our hearts on the spirit of New York. As we descend the stairs from the High Line, we look back one last time, taking in the panoramic canvas – the city, at once dynamic and soothing, the High Line, a poetic stand against ephemerality - a last, loving stroke that completes our New York painting with a signature flourish. Our journey may be coming to a close, but the memories made and the spirit of New York lives on within us, an indelible part of our travel story."
    }