// this code is generated from the story file kyoto_2023-11-10_23-15-53.txt
    // min_stops is set to 1

    package com.downdogapp.cue

    object SleepStoryTravelShortKyotoCues : SleepStoryPoseCues {

    override val start =
    "Ah, Kyoto, ancient capital of Japan, a city that gracefully blends the old and the new, the spiritual and the secular. Spring is the magical season when the whole city transforms into a celebration of newfound life, streets and parks bursting with hues of pink and white cherry blossoms. The gentle echo of bicycle bells, the soft rustle of silken kimonos, the distant hum of monks chanting, these are the ambient sounds that set the rhythm of the city. Today, we find ourselves at the beginning of a sightseeing tour, ready to embark on a journey through the city's historic landmarks and enchanting gardens on a traditional rickshaw led by a jovial middle-aged guide, whose eyes carry sparkles of countless stories yet to be told." /
"Our journey begins at the entrance of the famed Kinkaku-ji, also known as the Golden Pavilion. Our rickshaw glides to a stop at the entrance, our guide stepping down with a spry energy that belies his years and warmly ushers us into the temple grounds." /
"Kinkaku-ji leaves us breathless at first sight. It's perched at the edge of an elegantly designed pond, this Zen Buddhist temple carves a resplendent figure against the azure skies, the whole structure covered from top to bottom in golden leaf gleaming in the gentle sunshine. The effect is mesmerizing, the temple reflecting on the serene surface of the Kyoko-chi pond, creating a radiant spectacle against the lush backdrop of verdant trees." /
"Our guide, now turned storyteller, shares that this awe-inspiring temple was built back in 1397, meant to be a peaceful retreat for a certain shogun. Its style, he explains, was a nod to His desire to create a sense of harmony between heaven and earth, in line with pure land Buddhism’s principles. While we stand, captivated by the grand sight, our guide tells us that the original Kinkaku-ji was burnt down in the mid-20th century by a disgruntled novice monk, an event that later formed the heart of Yukio Mishima's celebrated novel." /
"Our focus soon shifts to the temple kiosks nearby, where we partake in the local custom of writing our wishes on small wooden tiles known as 'ema'. After we hang them up carefully, we savor some matcha green tea and wagashi, the sweet taste adding another layer of enjoyment to our temple visit. The tea's warm aroma mingles with the crisp spring air laden with heady cherry blossoms creating an irresistible blend." /
"As we leisurely sip the tea, we observe other visitors. Some local ones pray earnestly to the Buddha statues scattered around, seeking blessings or perhaps sharing some secret sorrow. International visitors, on the other hand, can't seem to get enough of the golden pavilion. Cameras flash continuously as they endeavor to capture the ethereal beauty of the golden temple and its surrounding landscapes." /
"Our journey by rickshaw to Kinkaku-ji has enriched us with countless moments of peace and tranquility, punctuated by the soothing narration of our amiable guide. His tales of local legends, similar to the temple we are visiting, paint the landscape with a magical air. As we prepare to hop on our bicycles again, eager to continue our exploration of Kyoto, the image of the majestic golden pavilion reflecting beautifully in the placid pond stays etched in our minds, sparking a bubbling anticipation for the wonders that still lie in wait." /
"Departing from the gleaming wonder of Kinkaku-ji, we continue our journey to the northeastern part of Kyoto, making our way toward the quiet serenity of Philosopher's Path. We still have our seasoned rickshaw guide with us, and his steady hands lead us with unhurried calm, allowing us to absorb every sight and sound." /
"We find ourselves on a charming stone path, winding its way through the heart of Kyoto's Higashiyama district. Our guide explains that the path, stretching approximately two kilometers, is named after the renowned philosopher, Nishida Kitaro, who is believed to have used the path for his daily meditative walks while he served as a professor at Kyoto University." /
"The landscape is mesmerizing, lavishly painted with the quintessential hues of spring as cherry trees line the canal in a signature floral formation. We become entranced by the sight of petals gently floating down the gentle stream with an almost philosophical grace. Our guide adds another layer of enchantment as he draws upon his vast knowledge of literature and poetry, referencing works that draw analogies between the tranquil setting and life's journey." /
"Deciding that our journey could use a break, we take a pause at one of the quaint cafes dotting the path. Here, we savor a divine bowl of udon noodles, each mouthful providing wholesome comfort. A warm cup of matcha tea complements our meal, and we find ourselves luxuriating in the culinary delights the path has to offer." /
"Along the path, we find ourselves sharing the experience with others - artists bent over their sketchpads, locals on a casual stroll with their dogs, tourists trying to capture the experience through their camera lenses, and children enchanted by the tame ducks who call the serene canal their home." /
"As our rickshaw ride nears its end, we decide to continue our exploration at our own pace, hopping onto rented bicycles for the next leg of our adventure. Alongside the canal, under the comforting shade of cherry blossoms overhead, we are enticed towards Arashiyama, an enchanting haven of towering bamboo." /
"The Arashiyama Bamboo Grove greets us; it's an otherworldly setting where the sky is a mere hint through the dense lattice of leafy bamboo tops. Here, the world stands still, the only perceptible movement being that of the bamboo swaying gently in the rhythmic symphony of the wind. Our guide tells tales of the bamboo's invaluable role in the local industry - how it has been harvested for centuries to create an array of goods such as mats, cups, boxes, and baskets, all handcrafted in local workshops." /
"Leaving the rickshaw, our now-trusted bicycles become our means of exploration. Traversing the grove, we can hear the rustle of bamboo leaves above our heads, an ethereal orchestration played by the cool wind. The tall bamboos provide natural shade, drawing a dramatic pattern of sunlight and shadows across the narrow path. The landscape is a living canvas, adjusting with the sun's movements, creating a spectacle that remains starkly beautiful as day dips into the late afternoon." /
"Nestled in this beautiful sanctuary are small restaurants and tea shops, each offering a brief respite from our journey. We pause once more, enjoying another Matcha tea while relishing traditional Japanese sweets, the taste a tender echo of the surrounding natural exquisiteness. As we continue, the last slants of the sun’s golden rays filter through the densely packed bamboo grove, each beam a path guiding us deeper into Kyoto’s enchanting landscapes."

    override val middle = listOf(
    "Leaving the serene expanse of the Arashiyama bamboo grove, we make our way towards the awe-inspiring Nijo Castle, our rickshaw smoothly gliding over the cobblestone streets, the steady rhythm lulling us into reverie." /
"As we come upon the castle, a sense of majestic grandeur takes over. Our guide tells us that the stone walls and moats surrounding the castle are designed to protect the Honmaru, the inner circle of the castle. Commissioned in 1603 by Tokugawa Ieyasu, the first shogun of the Edo Period, the castle serves as a proud testament to Kyoto's regal past." /
"Exploring Nijo Castle encompasses more than history; it is a walk through living art. From the lavishly decorated interiors of Ninomaru Palace to the famous 'nightingale floors' that chirp underfoot, designed to alert the guards of intruders, every arch and hallway holds a tale that has stood the test of time. As we walk through the palace, our eyes are drawn to the stunning wall paintings, masterpieces of the Kano School, their grandeur only amplified by the stories our guide shares about them." /
"Feeling a tad adventitious, we decide to sample Yudofu, a Kyoto-style boiled tofu, at a quaint eatery nestled along the castle's peripheries. The mild, silky tofu, often served in a warm soup with soy-based dipping sauces, proves to be surprisingly flavorful, offering a pleasant counterbalance to the rich history we've immersed ourselves in." /
"Leaving behind the regality of the Nijo Castle, we hop back onto our bicycles, making our way towards a more vibrant, everyday aspect of Kyoto – the hustle and bustle of the Nishiki market." /
"Tracing its roots back to a fish wholesale district in the early 1300s, Nishiki Market is now fondly referred to as “Kyoto's Kitchen”. As we cycle into the market, the lively atmosphere buzzes around us like electricity. The narrow, five-block-long street is brimming with an array of food stalls and shops, each offering an enticing aroma and sight that beckon us." /
"In the spirit of culinary adventure, we stop to savor Takoyaki, succulent octopus balls that Kyoto has put its own spin on, from a street food vendor. Venturing deeper into the market, we are tempted by an assortment of sushi and Kyoto's specialty pickled vegetables. The encounter with Kyoto's multifaceted cuisine wouldn't complete without a playful conclusion - a delightful scoop of Matcha ice cream that leaves us with the profound wholesomeness of powdered green tea encapsulated in a refreshingly sweet dessert." /
"Throughout the market, we notice locals sampling diverse foods, tourists admiring traditional crafts, and shopkeepers engaging in light-hearted banter. The entire area is a harmonious melody of local culture and community spirit that leaves us enriched, cherishing every bite and every sight as we continue our captivating journey through Kyoto.",

"Leaving the musky, lively market behind, we once again navigate our bicycles towards Kyoto’s more spiritual side. The knowledge and anecdotes of our charming rickshaw guide have been integral to our journey thus far, but today, we assert a bit of independence, pedaling off to Ginkaku-ji, or the Silver Pavilion." /
"Unlike its golden counterpart, the Silver Pavilion is a less ostentatious example of Zen temple architecture. Our guide had told us this elegant structure, also known as Jisho-ji, represented the Higashiyama Culture of the Muromachi period, a fascinating factoid that lends new layers to our viewing. The temple's calm, unassuming beauty becomes apparent with the first sighting. It seems to blend in harmoniously with its surroundings, embodying a rustic charm that's undeniably enchanting." /
"We learn that the Silver Pavilion was meant to be adorned entirely in silver foil, mirroring the Golden Pavilion's lustrous finish. However, this plan was never executed, and the timber of the structure has weathered into a graceful gray sheen, adding to its unique appeal. Off to the side, we spot the temple’s notable sand garden, its revered centerpiece being the 'Moon Viewing Platform’. This towering structure, shaped elegantly out of sand, is believed to symbolize Mount Fuji, its simplicity a testament to the Zen principles." /
"A stone's throw away from the temple is a quaint tea shop, where we stop for another traditional matcha session. The earthy aroma of the matcha tea paired with the subtle sweetness of the accompanying Japanese sweets creates a symphony of flavors, an experience further enhanced by the serene backdrop of the temple." /
"Other visitors flock around us, buzzing with intrigue and wonder. Some are caught in the tranquility of the temple’s beautiful moss gardens, others can't seem to put away their cameras, eager to capture the illustrious history of the Silver Pavilion in a tangible form." /
"As we bid farewell to Ginkaku-ji on our bicycles and ride into the approaching dusk, we transition once again, this time, into the grandeur of our next destination, the Kyoto Imperial Palace." /
"We arrive as twilight sets in, the soft glow of the setting sun a sublime backdrop to the regal silhouette of the Kyoto Imperial Palace. The palace grounds are embraced by long walls and dotted with meticulously maintained gardens, creating a serene atmosphere that's a world away from the city's bustle." /
"The palace's history is storied and intriguing. Serving as the residence of Japan's Imperial Family until the capital moved to Tokyo in 1869, the current palace is a testament to resilience, having been rebuilt numerous times after succumbing to fires. As we explore, we’re drawn to the Shishinden, the main ceremonial hall, with its immaculate architectural brilliance — an impressive testament to classic Japanese craftsmanship." /
"Around us, life unfurls. Visitors stroll around the expansive park, while others capture the historic buildings' regality with passion and curiosity. Some can be seen savoring green tea and traditional sweets in dotted tea shops, much like we did. Amidst all this, the pervasive beauty remains a consistent thread, said to be so profound that it is referenced in an old Japanese saying - “You cannot know the beauty of the moon without visiting the palace.”" /
"As the day wanes, the boundaries between tradition and modernity merge, each imprinting on our hearts a piece of Kyoto's versatile spirit. Imbued with the day's experiences, we pedal on, ready for what this city has in store for us next.",

"Bidding adieu to the tranquil surroundings of the Kyoto Imperial Palace, we set off once more, our rickshaw smoothly threading through Kyoto's picturesque streets toward our next mesmerizing destination - The Fushimi Inari Taisha Shrine." /
"Once we arrive, a scene of staggering beauty unfolds before us. Thousands of vermilion torii gates arc over the path that winds up a wooded hillside, forming a seemingly never-ending tunnel of vibrant color. Our guide informs us that Fushimi Inari Taisha is the head shrine of Inari, the Shinto god of rice, and that the enchanting array of torii gates has been generously donated by individuals and businesses seeking good fortune." /
"Our journey is accentuated by another soothing experience as we savor the unique taste of Inari sushi at a nearby stall. The sushi, an appetizing concoction of rice balls cradled by deep-fried tofu, is said to be favored by the foxes, the sacred messengers of the god Inari." /
"The lower reaches of the shrine reverberate with the cheerful chatter of visitors, some eager to capture this captivating vista in their lenses, while others venture off the main path, led by curiosity, into the tranquility of the surrounding bamboo forest. As we climb, peeling away from the throngs of visitors, the panoramic views of Kyoto reveal themselves, bathed in the soft, rosy glow of the setting sun." /
"Satiated by our immersive experience at Fushimi Inari Taisha, we resume our journey. Our next destination, the towering heights of To-ji, stands tall in the distance as we approach. It boasts the highest wooden tower in Japan and, we learn from our guide, it stands as a symbol of Kyoto. The pagoda is a magnificent sight to behold, especially against a backdrop of the vibrant cherry blossoms or autumn leaves." /
"This five-story pagoda, dating back to the early Heian Period, has been watched over by Kobo Daishi, the founder of Shingon Buddhism in Japan, ever since he was appointed head of the temple by Emperor Saga. We listen, enraptured, to the tales of Kobo Daishi shared by our guide that have been echoed through time in these very grounds." /
"Nestling into a local teahouse, we enjoy another comforting cup of matcha tea, this time paired with a Kyoto specialty: yuba, or tofu skin. Its delicate flavor and texture complement the robust matcha perfectly, further enhancing our culinary adventure." /
"Immersed completely in the cultural fabric of Kyoto, we venture into the renowned 'Kōbō-san' flea market, buzzing with activity around the pagoda. Here, everything from antiques to food is laid out in numerous stalls, as visitors from near and far gather to honor Kōbō Daishi on the 21st of each month. Engaging in the lively energy of the market, we mingle with locals, each stall offering its own little treasure to discover." /
"As twilight approaches and the sky paints itself in hues of pink and purple, we leave behind the vibrant atmosphere of To-ji Pagoda, our hearts filled with the day's rich experiences and eyes eager to embrace the upcoming allure of Kyoto’s nightscape."
    )

    override val end =
    "With a lingering sense of wonder from our visit to the To-ji Pagoda, we set off towards another serene spot in Kyoto, the much-acclaimed Kyoto Botanical Garden. The well-worn wooden wheels of our rickshaw, under the adept handling of our jovial guide, take us towards this beloved Mosaic of greenery, established in 1924, making it the oldest public botanical garden in Japan." /
"As we arrive, we find ourselves enveloped by a myriad of shades of green, punctuated by pockets of riotous colors. Spread over an impressive 240,000 square meters and home to over 12,000 species of plants, the garden feels like a living museum of biodiversity. Our guide points out the different sections - the Bonsai Exhibit, the Bamboo Garden, and the Camellia Garden among others, each an exquisite universe unto itself." /
"We then take a moment to pause at a quaint tea house within the garden, where we make little wishes before sinking our teeth into the traditional Hanami Dango, a skewered Japanese dumpling that tastes as sweet as the blossoms it is named after." /
"As we walk amid blooming cherry blossoms, navigating winding paths and quaint bridges, we notice other guests engaged in various activities - some artists are sketching the picturesque scenes onto their canvases, while local families are relishing in leisurely picnics, the children thrilled by the sight of koi fish darting about in the pond." /
"Feeling enriched by the Garden's astounding beauty, we mount our bicycles and head to our last destination for the day - Heian Shrine. The ride continues our experience of Kyoto in spring as we pedal alongside the serene Kamogawa River with transient cherry blossom petals carried aloft by the gentle wind, filling our hearts with peace and contentment." /
"Upon entering the massive red torii gate of Heian Shrine, we are awestruck by the monumentality of its architecture, which our guide tells us is a fantastic reproduction of the Imperial Palace from the Heian Period. The shrine was built in 1895 to commemorate the 1,100th anniversary of the capital's foundation in Kyoto, dedicated to the spirits of the first and last emperors who reigned from this city, Emperor Kammu, and Emperor Komei." /
"The garden in the shrine, Shin-en, is another spectacle in itself. With four distinct parts each representing the four seasons, the pure serenity emanating from the carefully curated plants and the well-pruned trees offer a peace that consumes us." /
"Among the visitors who are engrossed in prayer and those aiming for the perfect snapshot, we take our time savoring the lighter delicacy of Yatsuhashi, a sweet that is essentially Kyoto itself. A sense of tranquility fills the atmosphere as we glimpse over at others savoring the traditional sweet with us." /
"As the light wanes, we find comfort in the fusion of spirituality and natural beauty that is the Heian Shrine. We make a wish for a pleasurable ending to our day and with the strains of traditional music fading as we pedal away from the shrine, we're left with a sense of anticipation for the next day's adventures." /
"Energized by our vibrant and sensory-filled journey across Kyoto so far, we press on, eager for our next destination. The comforting clatter of our rickshaw wheels against the cobblestones and the friendly banter of our guide provide the perfect background chorus as we head towards the magnificent Kiyomizu-dera, more fondly known as the 'Pure Water Temple'." /
"Constructed entirely without nails, the wooden stage atop Kiyomizu-dera takes our breath away. This architectural marvel juts out from the hillside it rests on, throwing open vistas of Kyoto’s cityscape that seem like exquisite painted scrolls spread out beneath us. The temple was originally established in 778 by Sakanoue no Tamuramaro, but the current buildings date to 1633 — a testament to the preservation of the vision that first built it." /
"As we bask in the tranquil atmosphere, our guide passionately delves into the temple's history, his tales bringing a depth and admiration to our experience. He talks about the temple's namesake, the Otawa Waterfall. Running off the nearby hills, the fall’s crisp and clear waters lend the temple its title of Kiyomizu, which translates to 'clear or pure water'." /
"In the spirit of local custom, we sip from the waters of the Otawa Waterfall, each sip a small prayer that washes over us with a profound peace. Our guide shares with us the popular saying, 'to jump off the stage at Kiyomizu' – essentially a call to take a daring leap of faith. He shares the legend with warmth and humor that makes the incredible longevity of such traditions even more fascinating." /
"The glow of the setting sun lends a beautiful hue to our surroundings as we explore the other shrines in the temple complex. We take a pause at the famous Jishu Shrine, dedicated to the deity of love and matchmaking. Intrigued, we join in the light-hearted challenge of navigating between two stones, eyes closed, in hopes of finding true love." /
"Feeling peckish from our adventures, we indulge in yet another culinary delight that Kyoto has to offer. We savor the taste of Yuba, served in a variety of styles at the bustling restaurants around the temple. The experience leaves us satiated, the delicate flavors of the tofu skin cushioning our palate with a hint of the city’s culinary expertise." /
"Feeling content, we mount our trusty bicycles for a gentle ride downhill. The city unfurls beneath us with the splendor of a thousand poetic verses. Meandering calmly through peaceful streets, we're serenaded by the echoes of the day's explorations and the evocative beauty of Kyoto under the golden softness of twilight." /
"Our adventure through Kyoto's rich tapestry of history, culture, and natural beauty has been an immersive encounter - a dance through time where each alleyway, temple, and monument has spun a tale, drawing us into its mesmerizing rhythm. As we say our goodnights to the city and its pulsating spirit, with the quiet whisper of the rickshaw wheels and the gentle rustle of cherry blossom petals in the wind echoing in our ears, we long for the dawn that would once again awaken Kyoto, and with it, another day of enchanting adventures."
    }