// this code is generated from the story file costarica_2023-11-10_23-15-53.txt
    // min_stops is set to 1

    package com.downdogapp.cue

    object SleepStoryTravelShortCostaricaCues : SleepStoryPoseCues {

    override val start =
    "Tonight, we embark on a mesmerizing journey through the dreamy landscapes of Costa Rica, nestling ourselves comfortably in the wanderer's retreat that is a camper van. Our trusty four-wheeled sanctuary is not just transport, but home, kitchen, and viewpoint all bundled into one adventure-packed vehicle. Costa Rica, a veritable paradise that hums with life, blooms in technicolor, and gently sways to the rhythm of the Pacific, awaits us. Currently, it's the dry or 'verano' season, offering clear skies that mirror the vibrant blues of the sea and comfortable temperatures inviting exploration. Rich rainforests, enchanting wildlife, and warm, sandy beaches are aplenty, ready to etch memories in hearts and souls. As we prepare to set off, we can almost taste the anticipatory thrill rippling through the balmy Costa Rican air, each inhalation a promise of unforgettable experiences." /
"We ease into the journey with a visit to the celebrated Manuel Antonio National Park, renowned internationally for its staggering biodiversity and often deemed a gateway to nature's best-kept secrets. This maritime treasure vault of Costa Rica has 12 offshore islands frequented by playful dolphins and majestic migrating whales. Despite its humble size, it marks itself as a heavyweight in the country's ecological tapestry, capturing the awe of visitors since it opened its doors in 1972." /
"Underneath the rich, green umbrella of the rainforest, our camper van parked nearby, we acquaint ourselves with enchanting residents--howler monkeys echoing our excitement, three-toed sloths adorning the trees, and vivid scarlet macaws painting the sky with their bold hues. Every trail etches a story of a 100 species of mammals, each footstep introduces us to a new acquaintance, and every photograph captures a slice of Costa Rica's vibrant life. Along the trails, we savor a traditional Costa Rican Casado for lunch, delicious comfort food that energizes us amidst the encompassing wonders of nature." /
"As we listen to the harmonious melodies of the vibrant wildlife onboard, the untouched beaches and the undulating jungle gracefully reveal themselves. Behind these stunning vistas, the panoramic view of distant islands emerges like emeralds set in sapphire, completing a picture that beautifully captures the essence of Manuel Antonio National Park. With the map in our hands and our hearts filled with excitement, we find ourselves intertwined with nature, the soothing Costa Rican breeze whispering tales of what's to come in our ears." /
"Buoyed by the rejuvenating energy of Manuel Antonio National Park, we guide our trusty camper van through the undulating streets of San Jose, the heart of Costa Rica. Our first destination within the city is the prestigious Museum of Costa Rican Art. This cultural sanctuary, which has been nourishing the roots of local art since 1977, was once a bustling terminal, welcoming guests to Costa Rica's first international airport. Now it opens its doors to a different kind of traveler - the art lovers." /
"Underneath its historic moniker, the museum breathes life into Costa Rican artistry, from contemporary pieces to traditional masterpieces. We tread the smooth floors of the museum, carrying the aura of a hundred years of creativity. Our eyes skim over the captivating mural 'Costa Rican Life,' brush strokes of Francisco Amighetti resonating with vivacity on the canvas. We explore the expansive layout with a neatly folded map in hand. It’s a pursuit made sweeter by sipping on Costa Rican coffee from the museum's café, absorbing the delicate artistry nestled within the sculpture garden while partaking in traditional Costa Rican cuisine." /
"As we leave behind the artistic haven of the museum, we scoop up our eager anticipation and immerse ourselves in the infectious vibrancy of Mercado Central. For over 140 years, this bustling marketplace has served as an economic hub and a microcosm of Costa Rican societal life, teeming with over 200 shops and stalls and a smattering of sodas serving famished locals and fascinated visitors." /
"As we meander through the labyrinthine alleyways of the market, brimming with a multi-hued medley of fresh produce and artisanal crafts, the perfume of fresh fruits and the sizzle of traditional dishes seeping from the low-cost sodas draw us in. We join the rhythm of the good-natured haggling over prices and the hum of cordial chatters, savoring every note of the symphony of sensory experiences that is Mercado Central. Within the bustling confines of this sprawling market, we serendipitously find a new Casado dish to try, each bite an invitation to further explore the rich culture and palate of Costa Rica. The soul of San Jose unveils itself in these moments, painting our journey with vibrant strokes of Costa Rican life. Each discovery, from the museum's artistic brilliance to the market's vivid bustle, becomes a cherished memory in the diary of our Costa Rican voyage. As we navigate through, our journey through Costa Rica keeps unfolding into a tale of irreplaceable experiences and unforgettable encounters."

    override val middle = listOf(
    "Steering our camper van towards Arenal Volcano National Park, we trade the animated rhythm of San Jose for the tranquil cadence of Costa Rica's natural bounty. This remarkable park nurtures within its swaddling greenlands one of the world's most active volcanoes, standing as a testament to Costa Rica's seismic dynamism. Established in 1991, Arenal Volcano last asserted its vitality in 2010, and now stands as a silent guardian over approximately 121 square kilometers of verdant habitats." /
"A mesmerizing spectacle by day, the volcano reveals an entirely different mood when lit by the soft glow of the setting sun. Its legacy spills over to the landscape, with volcanic hot springs, aptly named 'Arenal' or 'pan of water' in native language, offering comforting warmth. While basking in this spectacle, we savor another serving of Casado, relishing the delicious alliance of rice, beans, plantains, salad, and a protein of choice served in local restaurants. As we laze in the comfort of the van, we're softly serenaded by the exotic calls of wildlife against the scenic backdrop of the volcano, an unforgettable scene reminiscent of Jorge Debravo's fiery portrayal of Costa Rica's mountains in his poem 'Tierra Enamorada'." /
"As the magnetic lure of Arenal subsides, we guide our trusted camper van towards the serenity that encompasses Tortuguero. The throbbing core of sea turtle conservation in Costa Rica. This conservation sanctuary plays sanctuary to the nesting homes of four remarkable sea turtle species - Leatherback, Hawksbill, Green, and Loggerhead. Since its establishment in 1959, it has served as the protecting shield for these integral marine beings, offering a haven amidst a world teetering on the edge of climate change." /
"Guided moonlit walks acquaint us with the astoundingly gentle nesting process of the turtles. Capturing these moments in our cameras and hearts, we find ourselves immersed in a poignant interaction unbeknownst to many. Dining next to the vast canvas of the pulsating sea, we relish yet another serving of the hearty Casado, the aromatic flavors intermingling with the scent of the ocean. In the pleasant hum of the coastal landscapes and the fascinating workshops about sea turtles, we find ourselves a part of beach clean-ups, contributing in our own small way to the preservation of these beautiful creatures. As we plant ourselves on the warm sand, gently lulled by the ocean's whispers, observing baby turtles embarking on their journey into the sea, we realize an invaluable truth - we not just mere spectators, but a crucial fragment of this intricate web of life. And thus, our journey continues, each turn cementing a bond with Costa Rica, embodying a tale of rediscovery and remarkable encounters.",

"Our journey takes a unique turn as we steer our camper van towards the heart of authentic Costa Rican coffee production, the Finca Rosa Blanca Coffee Plantation. A pioneer in sustainable, organic farming, the plantation has carved its unique niche within a UNESCO Biosphere Reserve, trading in the aroma of pure and finely brewed coffee. Walking through the coffee plants, we behold workers nurturing the rich soil, picking ripe coffee cherries with practiced hands, and scanning for unwanted guests among the plants." /
"The plantation, an oasis of over 5,000 native trees, welcomes not just coffee enthusiasts but also over 130 species of birds. The harmonious chorus of these feathered creatures beautifully soundtracks our exploration into the intricacies of coffee cultivation, an homage to Costa Rica's passionate coffee culture. Sitting in the heart of such historical richness, we indulge in a cup of high-quality, organic coffee, its strong, inviting aroma a testament to the farming traditions dating back to the early 19th century. The experience widens our perspective on the complexities cast behind each cup of traditionally styled Costa Rican coffee. Pausing to inhale deeply, we let the scent of blooming coffee flowers and the rich aroma of roasting beans fill our senses, a sensory prelude to the intricate dance of coffee creation." /
"Carrying the latent aroma of freshly brewed coffee and cherishing our coffee bean souvenirs from Finca Rosa Blanca, we guide our loyal companion on wheels towards our next enchanting destination, Playa Conchal. As the name declares in Spanish, the beach surprises us with its carpet of crushed seashells, a labor of love by the relentless ocean over centuries. A stunning vista of turquoise waters welcomes us, beckoning us into Playa Conchal's crystal-clear depths, a playground for snorkeling enthusiasts." /
"We share the sandy cognizance with sunbathers basking in the gentle rays of the Costa Rican sun and players engaging in a lively round of beach volleyball. Sampling the locally popular ceviche, the coastal flavors of the seafood dish adds another layer to our absorbing beach experience. Our camper van happily hunkers down by this shell-strewn beach, ensconced within the symphony of lapping waves, setting the stage for an immersive beach experience. As the sun dips into the horizon, we retreat into our camper van sanctuary, a rhythm of serenity encapsulating us, punctuated only by the ocean delivering whispered lullabies for a tranquil night's sleep. Each moment steadily become an integral note in the symphony of our Costa Rican voyage, the music of the journey shaping into a melody of discovery and affinity.",

"Returning to the embrace of nature, our camper van steer us towards La Paz Waterfall Gardens. Veiled in the tranquillity of Costa Rica's wildlife, this popular ecological attraction unfurls the country’s inherent magnificence. As we walk the well-maintained trail, we are greeted by fluttering inhabitants of the world's largest butterfly observatory, a myriad of colours spiralling in the air like a jubilant confetti. In the hummingbird garden, we enter a vibrant symphony of wings, our senses serenaded by the soft humming and the mesmerising iridescence of these tiny creatures." /
"Surviving the impact of a 6.1 magnitude earthquake in 2009, the fervour of life still pulses strong within the park, palpable in the electrifying energy of the resident wildlife and the emphatic gush of its five cascading waterfalls. At the Colibries Restaurant in the Garden, a buffet of traditional Costa Rican dishes awaits. As we savour every bite, we drink in the riveting sight and sounds of hummingbirds locked in their animated dance of survival. We carve a personal niche within the park by organising a picnic near one of the waterfalls, the experience heightened by the melodic crooning of the crashing water and the distant calls of native wildlife." /
"Bidding farewell to the Waterfall Gardens, we decide to bring the vibrant chorus of Costa Rican culture on board, along with the serenade of nature, steering towards the Sarchí Artisan Village. This cultural gem is the cradle of Costa Rica's oxcart tradition, its palette of vibrant colours and intricate patterns echoing a proud legacy dating back to the 19th century. The village's pride and joy unfolds before our eyes in the form of the world's largest oxcart, its presence in the village squares staking Sarchí's place in the Guinness Book of World Records." /
"The hand-printed patterns on the oxcarts, once a proud symbol of regional identity, are now an icon of national heritage, starring in the bustling theatre of the village's busy markets. Here, amid clusters of traditional Costa Rican dishes like Gallo Pinto and Casado, we mingle with fellow tourists, artists, and local vendors, the vibrant hum of life ringing in our ears. Exchanging tales, sharing meals, and browsing through the intricate offerings of traditional handicrafts, wooden furniture, and detailed ceramics, we infuse our journey with the lifeblood of Costa Rican tradition. As our cultural odyssey continues, we collect enduring echoes of raw nature and vibrant heritage, each imprint coaxing our camper van towards further corners of incredible Costa Rica."
    )

    override val end =
    "Guided by the spirit of adventure, our camper van makes its way towards the striking Rio Celeste, an extraordinary display of nature's alchemy within the Tenorio Volcano National Park. As we traverse lush trails accompanied by a symphony of exotic bird songs, the anticipation bubbles within us at the prospect of beholding one of Costa Rica's natural wonders." /
"Like the opening of an enchanting azure veil, Rio Celeste appears before us, its waters boasting an almost surreal blue hue. The river owes its stunning vibrancy to a unique interplay between the volcano’s minerals and sunlight. A cherished local legend breathes life into this scientific spectacle by suggesting the celestial blue was birthed when God, after painting the sky, cleaned His brushes in the river. Standing by the radiant river, we revel in the breathtaking sight, the moment punctuated by the eager clicks of our cameras. The exciting exploration leaves us with a hearty appetite and we savor a traditional Costa Rican meal of Gallo Pinto, the perfect blend of fried rice and black beans offering us a delightful endnote to our journey through the vibrant jungle." /
"Our next stop, the Pre-Columbian Gold Museum, offers a journey through time itself. Nestled beneath the Plaza de la Cultura, the museum is a gateway to Costa Rica’s golden age. Housing over 1,600 artifacts from between 500 AD to 1500 AD, the museum exhibits one of the most extensive collections of Pre-Columbian gold artifacts in Latin America." /
"Walking through the low-lit elegance of the 'Gold Room,' or Sala de Oro, the golden aura of the timeless pieces warmly bathes us. The detailed craftsmanship on display - figural pendants, animal figurines, ceremonial objects - whispers ancient tales that reverberate through the hushed halls of the museum. The gift shop offers a delightful surprise where we can claim a little piece of golden history in the form of a replica artifact. As we are leaving, casually chatting with sketching artists, admiring their renditions of the intricate designs, we feel a connection with the ancients who once thrived in these lands. We stand, lost in thought, before these beautifully preserved gold artifacts, each of us quietly contemplating the grandeur of a culture manifested in its golden legacy. The journey in our camper van continues, unfolding more of the rainbow tapestry that is Costa Rica, each thread revealing a new color, a new story." /
"As our Costa Rican adventure persistently unfolds, an air of quiet anticipation fills our camper van as we embark towards our final destination - the ethereal realm of the Monteverde Cloud Forest Reserve. A green jewel nestled in the heart of Costa Rica, this reserve stands sentinel over more than 10,500 hectares of rainforest, playing host to an incredible spectrum of life -- over 2,500 plant species, 100 species of mammals, 400 bird species, and a colorful flurry of 1,200 types of amphibians and reptiles." /
"In the enchanting depths of this reserve, concealed like a rare gem, is the feathered enigma that is the Resplendent Quetzal. Revered as mythical across many cultures, the sight of it is a nature-lover's dream come true. As we tread the countless trails threading through the vibrant green tapestry, cameras at the ready, each moment becomes a vivid memory, framed by the iridescence of exotic birds and the stunning panoramas of lush orchids clinging to towering tree trunks." /
"The resounding hush of the forest, punctuated only by the symphony of its teeming inhabitants, provides a soothing soundtrack to our gentle rambles. Amidst the damp coolness enshrouding the reserve, we find idyllic nooks to partake in local Costa Rican cuisine at quaint eateries, welcoming us with steaming plates of heartwarming Gallo Pinto and Casado." /
"Submerged in the heart of this green sanctuary, our camper van becomes our window to the unique atmosphere of the cloud forest. The cool mists wheel around us, transmuting sunlight into a spectral haze that weaves magic through the comfortable confines of our van. The living, breathing portrait of the cloud forest greets us as we look outside - an ampitheatre of greenery enveloped in mystical tranquillity. Distinctly, over the hush, we can hear the sonorous notes of the elusive Quetzal etching a melodic climax to our day." /
"As we retire into the comforting depths of our camper van, lulled by the whispers of the Monteverde Cloud Forest Reserve, our Costa Rican voyage appears as a splendid panorama. Each extrarordinary sight, every soul-touching moment, the vibrant memories, and the encounters that filled us with awe gently merge into a harmonious crescendo. Like a lovingly woven tapestry of adventures, Costa Rica unfurled into a symphony of breathtaking experiences, connecting us with an essence that's inherently Costa Rican - a joyful celebration of the riches of life, culture and astounding natural beauty."
    }