// this code is generated from the story file queenstown_2023-11-10_00-41-50.txt
    // min_stops is set to 1

    package com.downdogapp.cue

    object SleepStoryTravelQueenstownCues : SleepPoseCues {

    override fun Config.start() =
    "In hues of boundless blue sky, emerald green mountains, and a symphony of the tranquil lake's whispers, Queenstown, New Zealand, dutifully prepares itself as the epitome of summer perfection. Known as the gem of the Southern Alps, it nestles amidst the stunning ivory-capped peaks and the serene waters of Lake Wakatipu. Buffeted by the gentle mountain breeze, fragrant with the sweetness of blossoming flowers, the town twinkles in anticipation for the countless surprises it holds for curious visitors in the heart of summer." /
"The atmosphere is painted with a heartwarming, unhurried charm. The streets are filled with locals and travelers alike, the buzz of jovial conversations mixing with the gentle hum of nature. The water taxis glide seamlessly across the twinkling lake, ready to ferry eager passengers deeper into the sights and sounds of Queenstown. From time to time, they create soft ripples that lovingly lap at the shores." /
"Emanating the feeling of an adventure beckoning, the docks house small and cozy water taxis. They are ready to embark on a journey, a journey full of visual treats - majestic alpine landscapes, picturesque bays, and soothing coastal breezes. This comfortable and intimate mode of transportation invites us to truly immerse ourselves in the tranquil rhythm of Lake Wakatipu, silently narrating the soothing tales of this southern paradise." /
"With the warm glow of the sun overhead, a gentle breeze cooling the air, and the uplifting anticipation of the upcoming water taxi tour, Queenstown promises us an unforgettable summer journey. As we stand at the edge of this breathtaking canvas, we are gripped with joy and curiosity for the plethora of experiences that are about to unravel amidst the serene backdrop of nature's artistic symphony." /
"Docking our water taxi, we disembark from the serene vessel at the point where Queenstown Gardens reach out into the calm, glittering expanse of Lake Wakatipu. Established in 1867, we're reminded by our guide that we set foot on one of the oldest parks in New Zealand, a living testament to the history of Queenstown. It's an oasis within the city, a sanctuary where time seems to dawdle and invite us to stroll at leisure." /
"We begin a gentle exploration under a canopy of exotic and native trees, our footsteps softened by the lush carpet of grass flanking the well-worn paths. As we wander, we feel the sun delicately filtered through the interlocking branches overhead, creating a patchwork quilt of light and shade that dances across our path. A backdrop of mountains watches over us with silent majesty, their rugged beauty further highlighted by the lakeside setting." /
"Amidst the assorted shades of green, we notice an array of vibrant colors emanating from the Queenstown Gardens' Rose Garden. Here, roses in varying stages of bloom cast an intoxicating fragrance into the air, turning each breath into a celebration of nature's bouquet. We watch as an old woman with grey hair tied back into a loose bun, bends down to lightly stroke a particularly flawless bloom, a contented smile playing on her lips." /
"Soft laughter pulls our gaze away from the Rose Garden eventually, and we observe a group of young locals engaging in a friendly Frisbee game. Occasionally a shout of triumph echoes, adding to the garden's comforting soundtrack. A little further away, we spot an 18-hole disc golf course where families and friends challenge each other in a gentle test of skill and strategy, while sharing heartwarming banter." /
"The temptation for a break is too enthralling here. We — along with other visitors — spread our blankets over the comfortable grass near the Great Lawn and lay out a simple picnic. The taste of succulent New Zealand lamb and fresh local seafood along with the distinct and delicate flavors of wine from the Central Otago region enrich the experience, adding an element of sensory delight to our already indulgent afternoon. Laughter, conversation, and the rustling leaves create a soothing melody that fills the air and our hearts. Bathed in tranquility and delight, we pause to breathe deeply, allowing the elements of this harmonious blend to thoroughly soak into our memories."

    override fun Config.middle() = listOf(
    "Wrapping up our leisurely picnic at the Gardens, we gather our belongings and head back towards the lakeshore. There, the TSS Earnslaw Vintage Steamship waits patiently at the pier. A centenarian relic of Queenstown's history, her elegant form is a majestic silhouette against the crystal-clear waters of Lake Wakatipu. Launched in 1912, this vessel, named after the towering Mount Earnslaw, holds the prestige of being one of the last remaining coal-fired passenger steamers in the world." /
"As we step onto the steamship, nostalgia fills the air - it's as if we've been transported back in time. The aroma of the coal fire blends with the fresh mountain air, creating an intoxicating cocktail of past and present. Every detail of the ship, from the polished brass fittings to the soothingly smooth wood paneling, whispers tales from the early 1900s, reminding us of her service as a troop carrier and transport ship during World War II." /
"The old-world charm resonates even stronger as we peek into the engine room. Passengers, just like us, linger around to marvel at the exposed original steam engines. The rhythmic chugging and the flickering flames as the crew stokes the boilers strike a chord of harmonious simplicity, providing a tangible connection to the maritime technology of the past." /
"Amid the entrancing coal fire and steam, a whimsically quaint café on board woos us with the delightful aroma of classic Kiwi pies. We each buy one and settle comfortably as the journey begins. As the TSS Earnslaw pulls away from the pier, the steam whistle sounding makes our hearts skip as we head out, with the pie in our hands adding a layer of tastes and warmth to this wonderfully nostalgic sail." /
"The magnificent view of the Remarkables mountain range dances in and out of our vision as we make our way across the sparkling waters. As we sip our coffees, the sight of these majestic peaks through the steamship windows feel akin to delicate pencil sketches coming to life. Enjoying the journey aboard this vintage ship graced with so many stories and history, we sit back and chatter amongst ourselves, basking in the comforting embrace of a simpler era.",

"With the steamship returning us to the dock, we embark upon the next chapter of our journey. The energy of the group palpably shifts as we spot our water taxi for the next destination, New Zealand's only floating underwater observatory." /
"As this new ride undulates gently on the waters of Lake Wakatipu, the sun sheds a gentle light on the taxi's glossy wooden body. We step onto it, excited for the next segment of our journey. The water taxi soon sets course for the Underwater Observatory, sending soothing vibrations through the seats as the engine hums in harmony with the peaceful lapping of water against the hull." /
"The ever-dominant beauty of the Remarkables mountain range cradles the lake, presenting a breathtaking vista that paints the horizon. Their silver peaks boasting snow even in summer ripple along with the lake's serene surface, an eternally mesmerizing mirror." /
"As the taxi docks near the observatory, a unique structure quietly floating, we all rise with eager anticipation to disembark. Here, within a structure built in 1999, lies a whole other world. As we descend the stairs into the observatory, the world transforms. Submerged below the surface, we watch the fascinating spectacle of Lake Wakatipu's underwater life unfold. Tight schools of Brown and Rainbow trout swim past our view, their glistening bodies illuminated in the observatory's soft light. Native eels move with a serene and undulating elegance, their extraordinary length reflecting and refracting the light in psychedelic patterns." /
"Outside the observatory, children and adults alike gather around the surface, scattering breadcrumbs for the resident ducks and swans that float with deceptive calmness. The joy is apparent on their faces as they interact with these aquatic creatures, even making a few feathery friends." /
"Having immersed ourselves in Lake Wakatipu's underwater world, we feel a pull from our stomachs, signaling it's time for another local specialty. As we await our water taxi to progress back to the town, we indulge ourselves in green-lipped mussels, a treat New Zealand is famous for. The aroma wafting from the fresh mussels mingle with the scent of the water, their juicy and tender meat perfectly capturing today's theme of traversing marine life, making for an exquisite end to an underwater adventure.",

"After satisfying our taste buds with the delicious mussels, we find ourselves on the water taxi once again, this time headed to the south-western shores of Lake Wakatipu. Nestled in nature's lap, Walter Peak High Country Farm awaits us." /
"With the TSS Earnslaw guiding us, we journey nearer to the farm. As we approach, the awe-inspiring canvass of snow-capped mountain ranges commands our gazes, their stark beauty reflected in the pristine waters of Lake Wakatipu. It's a sight that compels us to join the others leaning against the ship's railing. Eyes wide in wonder, cameras flashing, we all soak in this powerful performing symphony of nature." /
"Stepping off the water taxi onto the 40,000 acres of breathtaking farmland, images from 'The Lord of the Rings,' filmed in these very surroundings, flicker through our minds. The enchanting valleys, emerald green hills, and the shimmering lake bring forth the cinematic grandeur of Middle Earth in shades of reality." /
"Thriving in the heart of rural New Zealand, the farm hums a melodious song of the countryside lifestyle. We see visitors all around, their hands occupied with spinning wool, a technique they picked up from the shearing demonstrations on the farm. Cameras flash every now and then, capturing moments of blending hues and smiles." /
"Among the rustic charm of the farm, we are lured in by the tantalizing smell of barbecue wafting through the air. Led by our noses, we find ourselves in the Colonel’s Homestead Restaurant, a traditional dining venue famed for its tender, farm-raised treats. Sitting down to a meal of New Zealand's finest lamb and beef, our taste buds tingle at the flavors dancing in our mouths, a tantalizingly rustic touch to crown our visit." /
"Comfortably sat amidst this amalgamation of rich tastes, merry camaraderie, and natural splendor, we delve deeper into the tranquil embrace of Walter Peak High Country Farm. With each glance shared with the animals of the farm and each footstep carefully placed on the soft grass, we echo with the pulsating rhythm of New Zealand's rural heartbeat.",

"Leaving behind the rural charm of Walter Peak High Country Farm, we gather ourselves for another delightful experience. Our water taxi carries us toward our next destination, cutting through Lake Wakatipu's serene waters. As we journey, Queenstown already begins to exhibit its different facet, shifting from rustic countryside to the subtle opulence of Matakauri Lodge, our soon-to-be oasis that is but seven minutes from the heart of the city." /
"As our water taxi approaches the lodge, we marvel at the harmonious blend of the mystical Lake Wakatipu, and the grandeur of the Cecil and Walter Peak mountain ranges. The scenery unravels with unparalleled splendor, making a renowned travel writer's words echo in our minds, 'Upon arriving at the Matakauri Lodge, one is immediately graced with an unobstructed view of the mystical Lake Wakatipu.'" /
"We disembark from the water taxi and make our way to this high-end lodge, first established in 2000 and refurbished by Virginia Fisher, an acclaimed New Zealand interior designer. Her touch has painted this place with a modern luxurious feel that radiates warm and intimate grandeur. In the main lodge, we see people gathered around the classy lounge and bar. Soft murmurs and clinking glasses mix with the soothing crackle of the fireplace. Some guests indulge in tastings of local wines from the Central Otago region, their smiles attesting to Otago's well-earned reputation for exceptional wines." /
"As the afternoon light subtly transitions, casting longer shadows but still maintaining the day's warmth, we sit down at our table in the dining area. A delightful afternoon tea awaits us, paired with an unhindered view of Lake Wakatipu. A selection of international dishes crafted with locally-grown ingredients is waiting to tease our taste buds. We serve ourselves to the introduction of this unique dining experience, gentle laughter and conversations buzzing around us, blending beautifully with the background of breathtaking landscapes." /
"Every little detail in the Matakauri Lodge speaks of elegance and grandeur, offering us delightful moments best captured not just in our cameras but etched in our memories forever. And as we savor the flavors of our afternoon tea while the Remarkables stand guard in the distance, every sip feels like a tribute to the enchanting beauty that is Queenstown.",

"Our water taxi adventure continues as we cast off once again from the exquisite Matakauri Lodge. The gentle hum of the motor and the soothing slosh of water beneath us accompanies our departure, setting a rhythm that seems in perfect harmony with the natural world around us. With the warmth of the sun on our skin and the panorama of Lake Wakatipu unfurling around us, our water taxi starts on a scenic route towards Paradise." /
"On this part of our expedition, the tranquil beauty of the lake gives way to unspoiled lush landscapes. Quite fitting to its name, Paradise bears no mark of commercialization. It basks in its untouched beauty, devoid of shops or houses, weaving its own timeless saga with nature's brush strokes." /
"Even as we near the shore, it feels like we are slowly floating into the pages of a classic literary epic. Peter Jackson's 'The Lord of the Rings' and 'The Hobbit' trilogies were filmed here, utilizing the breathtaking backdrops to breathe life into J.R.R. Tolkien's Middle-earth. We can imagine creatures of Tolkien's stories roaming around these very landscapes. This slice of paradise has also graced screens in the 'Wolverine' film and the award-winning television series, ‘Top of the Lake’." /
"Coming ashore, we find a quiet spot amidst this panorama of pristine beauty. The fragrance of untouched woodland fills the air as we lay out our picnic lunch, featuring a quintessential New Zealand meat pie. The sun-dappled landscape spreads around us like a verdant carpet as we indulge in this glorious outdoor dining experience, savoring bites of the delicious pie while our eyes feast on the surroundings." /
"Here, we encounter other sightseers, each assimilating the raw charm of Paradise at their own pace. Some are immersed in long tranquil treks, drinking in the gift of nature at every step, while others are busy capturing the ethereal beauty in their cameras. Witnessing the Kea and Bellbird flitting around, their songs echoing in this serene space, our own hearts sway in a tranquil rhythm, deeply connected to this untouched glory of nature.",

"Upon concluding our idyllic exploration of Paradise, we steady ourselves on the gentle ripples of the water taxi, heading towards the historic gold rush town of Arrowtown. As the town begins to unfold before our eyes, we find ourselves stepping into a cherished time capsule of the 1860s." /
"No sooner do we come ashore than the enchanting canvas of Arrowtown greets us. Depicting a living portrait of the gold rush era, the town's lifeline, the Arrow River, sparkles as an everlasting reminder of the golden attractions for prospectors of old. Casting our eyes over the river, we spot persistent and adventurous visitors meticulously panning for gold, their faces reflecting both concentration and delight." /
"Wandering through Arrowtown, we witness charmingly preserved miners' cottages at the Arrowtown Chinese Settlement. These humble homes speak volumes about the town's rich and diverse past, their stout structures a testament to the resilient spirit of the pioneers who built them. Amidst these vestiges of the past, visitors are found exploring boutiques and galleries, soaking in the seamless blend of history and modern-day life, savoring the breathtaking cinematography of the area that brought J.R.R. Tolkien’s Middle-earth to life in the 'Lord of The Rings' trilogy." /
"Our own exploration leads us to the Lake District Museum, an irresistible invitation to delve deeper into the tough pioneering days of the 19th century. Artefacts and exhibits stitched in time tell fascinating tales of the prospectors, the early Maori, and European settlers, who have shaped Arrowtown’s vibrant history." /
"With history lively and enthralling wrapping us in its essence, culinary adventure beckons us next. Stepping into a traditional tavern, murmurs of history and laughter blend with the savory aroma of an old-fashioned pub meal. As we enjoy this comforting fare, the echo of the past feels beautifully alive in the present within these rustic walls." /
"For those with a sweet tooth, the neighborhood's famous handmade fudge shops are a delightful pit stop – a sweet homage to the luxuries of the present firmly housed amidst an enduring past." /
"As the day gradually folds into evening, we meander across the town, guided by an old-town map, marking the heritage buildings scattered across Arrowtown. The town wears autumnal hues like a crown, painting a vibrant postcard that feels delightfully serene to the senses. Even as we retreat from Arrowtown, stocking up on local souvenirs and photographing bottlebrush trees vibrant with seasonal change, the living history, the charm, and the resilience of this gold mining town lingers with us, etched into our memory for times to come.",

"Shaking off the dust of the day spent exploring Queenstown's historical charm, we find ourselves ready for a distinct shift of scenery. The day's journey merges into a leisurely evening as we board our familiar water taxi once again, this time setting course for an oasis of modernity and sophistication - the Wharf Casino." /
"As the water taxi cuts through the darkened sapphire surface of Lake Wakatipu, the shimmering lights of the luxurious Wharf Casino gradually come into view. Established in the late 20th century, it's an impressive sight, its bright allure reflecting off the tranquil water, sparking an infectious feeling of excitement and anticipation." /
"Stepping off the water taxi, our senses buzz with the vibrant promise of the night. We enter the casino and are immediately welcomed by the warm hum of excited chatter, the clinking of glasses, and the enticing sound of rolling dice and spinning slot machines. The casino's luxurious interior unfolds before us, a play of soft lights and opulent decor skilfully blending sophistication and an invigorating energy." /
"Around us, people from all walks of life converge in this modern haven. Some gather around poker tables and roulette wheels, their smiles wide with thrill and anticipation. Others find their joy in the heels of the slot machines, their eyes shining with each spin. Novices and well-versed gamblers alike merge in an elegant dance of chance, finding common ground in the adrenaline-pumping games the casino offers." /
"As a counterpoint to the dynamic energy of the game, the casino extends another delightful experience in the form of a classic New Zealand dining experience. Moving away from the high-rolling buzz, we find ourselves at a quiet table, savoring the tender delights of Kiwi Lamb or Green-lipped mussels, each bite harmonizing with an exquisite glass of Central Otago Pinot Noir. The flavors manage to eclipse the gaming vibes briefly, entrapping us in a realm of culinary delights amid twinkling lights and engaging conversations." /
"In this whirl of exhilaration, the Wharf Casino becomes more than just a game of luck and fine dining. It's a circulating blend of human experiences - a stunning cascade of vibes, a riot of laughter, a hush of concentration, a sigh of satisfaction - each entering and exiting the grand stage, leaving behind stories untold, only to return in another captivating spin of Queenstown scenic charm and urban enchantment.",

"From the refined elegance and comforting hum of the Wharf Casino, our journey pivots towards an evening of thrill at the notorious Fear Factory. Within minutes, we find ourselves back on the pristine Lake Wakatipu, exchanging the merry clinks of casino glasses for the calm lapping of water against the boat. The soothing, peaceful boat ride forms a delightful contrast to the excitement simmering within us." /
"Standing against Queenstown's calm landscape, Fear Factory's building looms ominously, its supposedly haunted past casting long shadows over its present. Serving as a spooky tribute to classic haunted house and horror movie tropes, it successfully paints a picture of thrill, evoking a sense of both trepidation and exhilaration. Boasting real ghost stories from Queenstown’s dark past, the building seems to hold secrets that vie to escape the encasing walls, making it a popular attraction." /
"As the water taxi pulls into the dock, we join a group of other thrill-seekers waiting eagerly for a ghostly experience. The air vibrates with a cocktail of fear and excitement, an adequate fuel to prepare us for the night full of fun-filled horror that awaits within the Fear Factory." /
"Once inside, the eerie labyrinth plays tricks with the senses, startling even the most composed among us. It’s a delightful journey that twists our stomachs and sets loose an infectious laughter. Those emerging from the haunted building carry exhilarated expressions of triumph, their eyes alight with frightful memories." /
"With hearts still pounding and adrenaline rushing through our veins, we end the thrilling journey, stepping into the cool, night-time air of Queenstown once more. The calm night provides a perfect backdrop as we make our way to nearby pubs to unwind, sharing stories and recounting the horror-filled delights that Fear Factory served us. Their warm interiors, laughter, and cold beverages provide a soothing refuge from the adrenaline-fueled experience, allowing us to bask in the evening’s excitement." /
"The night secures the essence of Queenstown within each of us, a myriad blend of scenic beauty, history, cuisine, thrilling games, and spooky delights all tied together with a crew of strangers who turned into friends.",

"Leaving the spirited night behind and carrying the echoes of ghostly laughs, we step into another day. As the morning light bathes Queenstown, we board our water taxi once again, this time headed for an ever-upward adventure to the top of famed Bob's Peak. Across the shimmering surface of Lake Wakatipu, we glide, the journey creating perfect mirror images of the surrounded mountains, haloed by the morning mist." /
"Upon landing at the base of the steep incline, we gather ourselves, anticipation and excitement bubbling conveniently beneath our collected demeanors. As we leave the gentle lapping sound of the lake, the gondola ride before us beckons us. Adventure is etched into its very design, as this is the steepest cable car lift in the Southern Hemisphere, a ride that promises a bird's eye panorama of Queenstown." /
"Once inside the gondola, we marvel at the rising scenery. The earth gracefully pulls away as we ascend, offering an ever-changing backdrop of Lake Wakatipu and the rugged beauty of The Remarkables mountain range. As we near the top, our hearts flutter with the breathtaking spectacle of Queenstown’s surroundings. The lofty peaks encircle the tranquil lake, painting a panorama that takes our breath away, and we now understand why it's considered the best view of Queenstown." /
"Bob's Peak, named after local identity Bob McKay, is rich in more than just its natural splendor. As we disembark from the gondola, we're once again treading the grounds of many scenes from the much-loved Lord of the Rings films, turning our adventure into a subtle journey within Middle-earth itself." /
"Our stomachs guide us to the Skyline Queenstown Restaurant, situated atop Bob's Peak. Here, at the blend of food and foliage, we treat ourselves to a delightful buffet. A mouth-watering symphony of local and international dishes against an unbeatable scenic backdrop invigorates us as we feast our senses on the culinary and visual delights." /
"Post-meal, we see many of our fellow visitors gearing up for an adventurous trek down the scenic trails of Bob's Peak. The trails echo with the laughter of those daring enough to mountain bike their way down. More enthusiastic shouts join the chorus from those enjoying the thrill of the Luge rides, cutting through the quiet murmur of conversations." /
"As we laugh, explore, and soak in the elevated views of nature's extraordinary canvas, we celebrate yet another day of our journey. With every new sight, sound, and experience at Bob's Peak, we weave a richer tapestry of our Queenstown adventure, promising to carry it with us when we descend back down to the waiting water taxi.",

"Emerging from our visual and emotional exhilaration atop Bob's Peak, we find ourselves yearning for an experience that indulges in touch, taste, and aroma. Our water taxi emerges as our trusty steed once again, ferrying us towards the serene countryside setting of Gibbston Valley." /
"Christened as the 'Valley of Vines', Gibbston Valley lives up to the grandeur of its name. As the coolest and highest wine area of the Queenstown-Lakes District, its vineyards sweep across the valley, a breathtaking, undulating sea of green, basking in the generous New Zealand sun. The scene evokes an artistic tenderness, a vision often showcased in renowned culinary magazines, revealing why this valley is the undisputed home to some of the most premium wines in the region." /
"Gently docking at the valley, we set foot in the home of Central Otago’s first commercial vintage released back in 1987 by Gibbston Valley Winery. The aura of decades marries the tang of vineyard air as we revel in the idyllic countryside charm." /
"Taking the vine-clad path to the wine tasting tour, we are met with an array of exquisite varietals patiently waiting to be poured, sniffed, swirled, and tasted. The valley's famous Pinot Noir, Riesling, or Chardonnay weave intricate tapestries of their rich heritage and precise cultivation on our eager palates. Each sip reveals the skillfully nurtured nuances of the fertile New Zealand soils, the crisp air, and the loving attention to bottling such delicious symphonies in these glasses." /
"As we heighten our palate experience, we partake in the rich variety of locally sourced cheeses in the valley. Each bite deepens our appreciation for the art of fine pairing and the harmony of texture and flavor it brings forth." /
"Between sips and bites, the day progresses, seeing us eager visitors exploring the wine cellar and touring the vineyards. We watch with respect as our fellow enthusiasts enroll in wine and cookery classes, a testament to the valley's wine-infused inspiration and insistence on sharing its knowledge with others." /
"Relishing the bouquet of wines, cheeses, and breathtaking vineyards in the Gibbston Valley, we sway with our own rhythm, slowly absorbing the confident yet humble charisma of the region. Amid sunny vineyard rows, cool cellars and the whisper of fine wines, we immerse ourselves, footfall by footfall, in the sedate rhythm of the beautiful 'Valley of Vines', a delightful painting in our Queenstown tour palette.",

"As the sun begins its descent, painting the sky with warm hues, we leave the vine-clad paradise of Gibbston Valley behind, ready to embrace the magical whispers of the Kiwi Birdlife Park. Ensconced in the heart of Queenstown, this family-owned wildlife sanctuary emerges onto our journey like a beautifully illustrated chapter of a captivating storybook." /
"Another pleasant water taxi voyage rewards us with stunning views of Lake Wakatipu and glimpses of rare New Zealand flora and fauna. The wave-kissed journey stirs anticipation within us as we approach this serene haven, contributing more than 30 years to bird conservation efforts with over 150 feathered friends released into the wild." /
"Stepping into the sanctuary, our attention is immediately claimed by the gentle rustling and soft chirps resonating from its green heart. A guided tour leads us to the Night House, a setting crafted to mirror the natural nocturnal environment of the beloved Kiwi bird. In the muted lighting, the legendary birds command our complete fascination as they wander, probe, and play within reach yet respectfully distanced. Their unique charisma embodies their namesake country's ardor for conservation, a lesson observed in every movement they make." /
"Yet, the sanctuary's marvels extend beyond its namesake inhabitants. The Kiwi Birdlife Park houses over 20 species of native New Zealand wildlife, each weaving its own mystical tale within the ecosystem. At every turn and every trail, the park offers an intimate peek into the lives of these creatures, a live documentary set within the frames of lush greenery." /
"The sanctuary intersperses soothing experiences with some cultural infusion by presenting Maori culture shows. The rhythmic songs and traditional dances provide a beautiful blend of entertainment and enlightenment, mirroring the harmonious co-existence of humans and nature in New Zealand." /
"As the day folds into an enriched evening, we embark on a serene nature walk through the park. The meditative tranquility, punctuated by bird calls, immerses us in a warm symphony that crescendos into a perfect closing note to the day's memorable escapade. As we tread gently through the nature trails and whisper our goodbyes to this sanctuary woven with feathers and flora, the Kiwi Birdlife Park remains aglow beneath the stars, a lively painting imprinted upon our hearts.",

"Our night rejuvenates us for the day ahead, which begins with a beckoning call from Tobins Track. Named after John Tobin, an early settler in Arrowtown in the late 19th century, the track presents an invitation to trade water taxis for hiking boots. We answer this call excitedly, donning our gear and bidding a brief farewell to the alluring Lake Wakatipu." /
"As we commence the ascent, each step carries us higher on this 5.4 km long back trail nestled near Arrowtown. It's become a path to discovery for nature lovers, winding through a picturesque canvas that invites hikers to immerse fully in the unspoiled serenity it offers." /
"The steep trail teases us with fleeting glimpses of the scenic grandeur awaiting us on the summit. As we engage in the steady climb, our determination is rewarded by progressively widening panoramas of the historic gold mining town of Arrowtown, Lake Hayes, and the expansive Wakatipu Basin. It's a spectacle that unfolds petal by petal, akin to a flower revealing its inner beauty to the morning Sun." /
"Upon reaching the summit, we're greeted by a breathtaking view, an unrestricted visual of the charming Arrow Basin and the majestic Crown Range. Here at the top, a local tradition invites us to unwind, unfurl our picnic blankets and enjoy a well-earned rest. The classic New Zealand meat pie finds its place as our meal of choice, its delicious savory treat melting seamlessly into the spectacular backdrop." /
"Around us, the summit resonates with vibrant life. Fellow travelers, their faces flushed with climbing satisfaction, engage in various activities that dot the landscape with charm. Nutrient-laden soil provides the perfect footing for those flying kites in the clear expanse of the sky. Others rest, their lenses capturing panoramic images that can scarcely house the visual feast on offer." /
"Amid the whispers of the gentle wind, the singing birds, and the rustle of grass under the soft footfalls, Tobins Track joyfully echoes with our laughter. Nestled in nature's untouched beauty, the day gives way to a satisfying tiredness, the kind that enriches the spirit. As we begin our descent, we look back at the summit with warm smiles, the day's experiences forming a lovely garland of memories around the trail and in our hearts.",

"As another day dawns in the scenic embrace of Queenstown, we find ourselves aboard our faithful water taxi, heading towards a new adventure. Nestled in the heart of the South Island, Coronet Peak stands as a beckoning sentinel, her slopes whispering tales of human endeavours and nature's grandeur. Being South Island's most popular ski area and one of New Zealand's oldest ski fields, Coronet Peak ushers in a promise of thrill, beauty, and a deeper connection to the region's cultural tapestry." /
"Our journey towards the mountain carries us across the clear blue waters of Lake Wakatipu. The panoramic spectacle of Cecil Peak, Walter Peak, and the charming cityscape of Queenstown unfurls in a dynamically shifting view. Seagulls trace graceful arcs in the bright sunlight overhead, their call a melody in sync with the rhythmic lapping of the water against our water taxi." /
"As we dock and embark a shuttle up to the Coronet Peak ski field, the view only magnifies. In the Maori culture, this place of significance is known as 'Hikuraki', a name recalling legends and stories woven around the mountain, adding a reverential depth to its natural splendor. The appreciation of this sacred locale only sharpens when one recalls that several scenes from 'The Lord of the Rings' Trilogy were filmed amidst this breathtaking landscape." /
"Upon reaching the top, the world seems to lay beneath us, the grand expanse of Queenstown spreading on one side while the sky, an endless dome of brilliance, arches on the other. Seeing fellow visitors strap their skis or snowboards in winter, or lace up their hiking boots in summer, the spirit of outdoor adventures embodies the essence of Coronet Peak." /
"When the chilly mountain breeze cuts sharp, or after a particularly taxing trail test, the Coronet Peak Restaurant becomes our refuge. Here, the delectable aroma of warming hot chocolates and aromatic mulled wine complements the splendid views outside the restaurant windows. The cosy atmosphere imbues our meal with a serene satisfaction that only enhances the grandeur outside." /
"From enjoying the hearty meals to soaking in the stunning panorama, or indulging in the thrill of the slopes and trails of Coronet Peak, the day proves to be a harmonious blend of excitement and tranquility. As we descend after the sun dips beneath the horizon, stars start peeking out in the vast expanse, as if to shower their twinkling approval upon our unforgettable day at Coronet Peak.",

"Leaving the momentous Coronet Peak behind, we turn to mingle with Queenstown's waters once again. An air of excitement and adventure grips us as we embark on a water taxi destined for the renowned Shotover River. A vibrant thread in New Zealand's rich history, Shotover River sparkles with traces of the gold rush era, earning it the title of 'the richest gold-bearing river in the world'." /
"As we glide over the flowing turquoise ribbon, the river embraces us with its rhythmic song, carrying echoes of its Maori name meaning 'the place of the rushing waters'. Leaving the calming expanse of Lake Wakatipu, we now find ourselves facing the thrill of Shotover River's playful rapids as it ribbons its way through the stunning Skippers Canyon." /
"The striking canyon walls, filmed in epic 'Lord of the Rings' scenes, tower above us, casting shifting patterns of light and shadows on the river's surface. The insistent roaring of the rushing water forms an exhilarating symphony with the rumbling engine of our water taxi. It's an adrenaline-spiked ride through the heart of untamed wilderness, the water intermittently spitting up in soft sprays against our faces." /
"Halfway to our destination, we give ourselves some respite, anchoring on a calm bend of the river for a delightful picnic. Traditional New Zealand pies filled with succulent minced meat emerge from our picnic baskets. As we savor the hearty Kiwi delicacy, the Shotover River hums contently beside us, offering a unique blend of serenity and electrifying energy." /
"With our appetites satiated and adventure-lust rekindled, we witness the Shotover River serve as a playground for the daring, with jet boats masterfully gliding over the waters, and visitors bobbing along in rafts against the powerful current. Each roar and splash reflecting people's youthful exuberance, we step back into our water taxi, the taste of the river's wild charm still lingering in our mouths." /
"As we resume our journey down the Shotover River, enveloped by the splendid beauty of the Skippers Canyon, each spray of the water and sweep of the landscape deepens our connection with the river's spirit. Shaped by history, shaped by nature, the river shapes us in turn as we cruise deeper into the heart of Queenstown, carrying the day's memories as cherished souvenirs.",

"Setting foot on another water taxi, we leave the thrilling company of the Shotover River to navigate towards a completely different vista. This time, our destination holds renown, not for its natural beauty but for the beautiful portrayal of it by a gifted hand - the Ivan Clarke Gallery." /
"As we glide across Lake Wakatipu, the serenity of the journey offers a delightful contrast to the pulsating adventure of the day. The idyllic vista of mountains mirrored in the lake's still surface and the joyous ballet of indigenous birds around the reeds form an alluring precursor to our artistic escapade." /
"Docking near the gallery, the enticing aroma of coffee teases us from a nearby café, an irresistible invitation we happily accept. Nestling warm cups of flat white coffee, an iconic representation of New Zealand's rich café culture, we relish the creamy comfort of each sip before surrendering to the creative allure of the Ivan Clarke Gallery." /
"Stepping into the gallery, we are enveloped in the artistic universe of renowned New Zealand artist Ivan Clarke. Seemingly alive with emotion and mysticism, his depictions of New Zealand's landscapes transfix us. The stirring expressiveness of 'Alone in a Midnight Garden' captures our hearts as we stand before it, the painting's influence resonating strongly from its tours to London, New York, and Hong Kong." /
"But the gallery extends beyond these richly textured landscapes - as we explore, we soon encounter the immersive experience 'The Lonely Dog,' which showcases Clarke's charmingly imagined 'Kingdom of Alveridge.' This artistic storytelling invites participation and deeper exploration, infusing the gallery visit with a sense of playful enchantment." /
"Our wanderings among the intricate details of Clarke's works soon lead to meaningful interactions with fellow art lovers. Engaging in lively discussions about the artwork further deepens our understanding of and admiration for Clarke's art. To our amazement, we even get to engage in a personal tete-a-tete with the artist himself, who we find sharing the inspirations and stories behind his artistic creations within the gallery." /
"As the day stretches into the evening, each light and shade within the Ivan Clarke Gallery enhances the magic of the art within. The gallery visit blooms into a seamlessly woven blend of serene landscapes and our own emotional journey, delicately tinted by the spellbinding artistry and the beautiful narratives of Ivan Clarke. As we step back into the twilight, the memories of this artistic sojourn leave an indelible imprint on our hearts, a fitting close to the day's journey.",

"The dawn of a new day stirs Queenstown from a tranquil slumber, the sun casting its first rays across the snow-dusted peaks of the surrounding ranges. With our hearts brimming with anticipation, we once again find ourselves on a water taxi, this time set to venture into the heart of one of New Zealand's most significant and dramatic natural phenomena – Fjordland National Park." /
"As our water taxi sets course for the largest national park in New Zealand, the tranquil lake waters give way to the imposing fjords. Established in 1952 and recognized as a UNESCO World Heritage Site in 1986, the park spans a staggering 12,500 square kilometers of untouched wilderness. We marvel at this vast expanse, where the raw power and inherent elegance of nature display a timeless performance." /
"Into the depths of the park we journey, gliding silently along the serene fjords undercut by the towering Mitre Peak. Here, untouched by modern civilization, the world unfolds in its purest form. The gentle slopes tumble to meet the sapphire blue fjord, the peaks dusted in snow, a hushed testament to its namesake, Milford Sound, accessible only by boat or helicopter." /
"As we flow with the fjord's calm rhythm, wildlife enthusiasts and photographers are a common sight on this trip. Equipped with binoculars and cameras, they wait patiently to capture the perfect image of the stunning landscape and the park's diverse fauna. Occasionally a friendly pod of dolphins join in, their sleek forms escorting our water taxi, surfing effortlessly in our wake on this sunny New Zealand day." /
"In need of a pause, we anchor our taxi alongside a quiet inlet. Surrounded by the spectacular scenery, we savor a delightful packed lunch, taking occasional breaks to take in the breathtaking views. Each bite tinged with the pure atmosphere, merging with the awe and tranquility that inhabits this unique corner of the world." /
"In the heart of Fjordland National Park, we experience a captivating dance between shy glimpses of wildlife, the majestic fjords, and our own reflections. In every ripple that gently rocks our water taxi, every beam of sunlight illuminating the diverse fauna, and every delicious bite of our picnic, the park gradually reveals a part of itself, infusing this journey with an ever-lasting memory of New Zealand's raw beauty.",

"Departing from the serene embrace of Fjordland National Park, our hearts pound with expectancy as we board the water taxi once more. This time, our journey transforms into a passage through movie magic, the very crafting of Middle-Earth amidst the phenomenal New Zealand landscape. We turn our sights to the filming locations of the award-winning film trilogy - 'The Lord of The Rings'." /
"As we navigate the tranquil waters of Lake Wakatipu, the iconic mountain ranges and enchanting forests fall into our view - a sight and setting so captivating that director Peter Jackson deemed it the perfect choice for a fantasy epic. The beauty of Queenstown melds seamlessly with the illusion of Middle-Earth: the 'Ford of Bruinen', where elves dwell and horses of water gallop; the towering 'Pillars of the Kings'; and the golden forests of 'Lothlorien', a testament to the region's picturesque charm." /
"Against the backdrop of these cinematic landmarks, we find ourselves remembering poignant dialogues from the film. And as we set foot on each filming site, J.R.R Tolkien’s legendary line rings true in our hearts: 'It's a dangerous business, Frodo, going out your door. You step onto the road, and if you don't keep your feet, there's no knowing where you might be swept off to.'" /
"At each location, an infectious wave of enthusiasm ripples through tourists around us. There is a playful air as some tourists indulge in lively reenactments of the film scenes. The creativity only enhancing as they pose for photos against the majestic landscapes, their faces aglow with joy and bubbling laughter piercing the calm tranquillity of the area." /
"After immersing ourselves in the film's iconic scenes, we delight in a traditional New Zealand lamb dish, a culinary highlight of the tour's picnic lunches. Sitting on the lush grass, with the remarkable backdrop of Middle-Earth scenery, the flavorful bites meld with the awe-inspiring surroundings, creating an experience worth savoring." /
"The day reaches a fulfilling end as we head back on the water taxi, each carrying golden fragments of Middle Earth in our hearts and memories. Over shared thermoses of hot tea and coffee, we chatter animatedly, swapping memorable moments from the tour and the films. Each ripple in the water and every mountainside bathed in the evening light holds a piece of the Middle-Earth magic, echoing long after we step off the taxi, back to our lodgings, every smile filled with unspoken tales of our Middle-Earth escapade.",

"Having journeyed through Middle-earth, we step onto the familiar deck of our water taxi for our next encounter with Queenstown's natural grandeur. The day's adventure brings us to the enchanting Lake Hayes, warmly referred to as the 'mirror lake' owing to its stunning reflective surface." /
"Nestled within the Wakatipu Basin in Central Otago, Lake Hayes quietly ushers in a vision of unruffled waters, seamlessly capturing the image of the soaring mountain ranges and lush vegetation in its undisturbed surface. We marvel at the mirror-like reflections, a sight so appealing that it has been depicted in countless photographs and has inspired many New Zealand artists over the years." /
"The history of the lake further enriches our journey. Traditional Maori legends recite tales of battles and romance along this lake's shores, casting echoes of the olden days that resonate with each ripple on the glazed surface. As we circle around the famous Lake Hayes Circuit, every lookout point and every moment rewards us with these stories, weaving themselves into our exploration." /
"Dotted along the banks of Lake Hayes, visitors animate the tranquil scenery. We watch delightedly as kayakers and paddle boarders artfully maneuver over the lake's calm waters, their movements creating mesmerizing patterns in the water." /
"Deciding to join in, we find a cozy nook for ourselves along the lakeside. Unwrapping our packed picnic, the tastes of New Zealand's artisanal kumara bread and local cheeses mingle with the crisp notes of the applauded Pinot Noir wine from the region. Each bite and sip is a testament to the local flavors, fighting for attention with the surrounding picturesque scenery." /
"Immersed in this sensory symphony, Lake Hayes weaves its spell around us. Every kayaker cruising the lake, each soothing ripple morphing into mirrored images, all under the watchful eyes of the peak-ringed horizon, constructs a serene canvas. Reflecting on the sun-kissed waters of the 'mirror lake,' we embrace the day's gentle memory, all of which follows us onto the waiting water taxi for our journey back. The ethereal beauty of Lake Hayes flickers behind us as the taxi pulls away, bound to illuminate our reminiscences for years to come."
    )

    override fun Config.end() =
    "Our sightseeing tour continues as we head towards another gem of Queenstown. With a historical foundation embedded in the rockface itself, the Skippers Canyon waits for us just a water taxi ride away." /
"Carved out in the gold rush era of the 1890s, the Skippers Canyon is, in its own right, a grandiose testament to a bygone era. Named after 'Skipper' Malcolm Duncan, a local gold prospector, the canyon tells tales of times past, when the quest for gold dictated the rhythm of life." /
"Once on land, we find ourselves on an impressive road, it’s path clinging to the cliff face precariously. But it's not just the man-made road that captures our attention. The stunning natural scenery is a spectacle in itself, so captivating that it played a part in Middle-earth itself in the Lord of The Rings film series." /
"Suspended among these natural wonders is a marvel that stands as a proud relic of history - the Skippers Suspension Bridge. Constructed in 1901, the bridge diligently fulfilled its function as an essential passage for gold miners. Its weathered visage against the majestic canyon holds us captive with an undeniable respect for its chronicle." /
"Embracing the magnificence of the canyon's vista, we find a comfortable spot for a delicious culinary adventure. With a breathtaking view spread out in front of us, we tuck into a traditional Kiwi barbecue, savoring the local lamb, beef, and seafood gracing our plates in true New Zealander style." /
"Amidst our feast, sightseers around us indulge in the canyon's tempting offering of adventure. The roar of the Shotover River, which threads its way through the canyon, calls out to adrenaline seekers. River rafting and bungee jumping activities beckon the daring ones, their excited screams echoing amidst the silent canyon walls." /
"Once our meal is complete, we embark again on the water taxi. As it navigates the Shotover River, the steep cliffs and jagged rocks of the canyon jump into perspective, their rugged face a stark contrast to the serene ride. A heartbeat of surprise tugs at us when we spot a group of wild goats, skillfully navigating the treacherous terrain. Their nimble dance against the golden-hued canvas of the canyon adds a thrilling chapter to our day's adventure. This intimate moment of connection with this raw, challenging yet beautiful part of nature leaves engraved a lasting memory as we continue our explorations of Queenstown's scenic treasures." /
"Steeped in the wild echoes of Skippers Canyon and still carrying scents of the Kiwi barbecue, we find ourselves on the water taxi once more, the day's journey drawing towards a peaceful conclusion." /
"As the sun dips into the horizon, painting the Queenstown skyline with hues of twilight, the cool mountain air carries whispers of the day's adventures to our ears. The soft ripples in the sapphire expanse of Lake Wakatipu dance in gentle tandem with our tales of labyrinthine galleries, gold-rush trails, revered sanctuaries, and the wild beauty of a land where humans and nature have danced a harmonious waltz throughout history." /
"The everyday chatter in the water taxi becomes hushed, as if momentarily silenced by the symphonic serenade of the encircling peaks. Nature's grand opera of the stars begins to reveal itself above, the cosmos blinking into view one by one, the celestial sparkle a fitting tribute to our day, mirroring the joy-filled twinkle in our eyes." /
"Embracing the cloak of the cosmos above and the gentle lapping of the water below, we pull closer on the water taxi. With warmth between us, we share silent promises to remember the places, the faces, and the emotions that colored our journey through Queenstown. We quietly marvel at how our reflections in the lake's mirror pull the celestial spectacle closer to us - a tapestry of shared experiences under nature’s vast, starlit pageant." /
"As the last ripples of our journey echo in the waters of Lake Wakatipu, we draw comfort in knowing we traversed not just a city but the generous spirit of Queenstown. The whisper of the wind ensures we carry home a slice of tranquillity, remnants of a joyous feast, the brave spirit of adventure, and a lingering symphony of a journey that has forever etched Queenstown in our hearts." /
"Assured with these memories and the comforting pulse of the water beneath us, we allow the steady hum of the water taxi to lull us into a blissful harmony, serenading us with a gentle lullaby as we dream under the New Zealand sky - a perfect ending to our Queenstown adventure. As the stars shimmer, each twinkle is a promise of new stories awaiting us under the Southern Cross, calling for another serene exploration, another peaceful adventure, and another soothing journey that awaits us tomorrow on the sparkling waters of Lake Wakatipu. With the ebbing wave of a heart, our story today finds its tranquil shore, softly winking us good night."
    }