package com.downdogapp.cue

object SleepStoryTravelNewyorkcityCues : SleepPoseCues {

override fun Config.start() =
"Welcome to the transcendent fall season in the city that never sleeps, New York, New York. Known for its vibrant kaleidoscope of colors, picture skyscrapers, caught in the mesmerizing autumn hues of ocher, burgundy, and copper. Leaves flutter gently to the ground in Central Park, blanketing the crisscrossing paths, while the aroma of roasting chestnuts wafts through the cool crisp air. The city, cut from an undulating tapestry of rich cultures and history, begins to take on a magical quality." /
"Today, we explore this magnificent metropolis by open-top bus and Metro. Perhaps it's the soothing drone of rubber tires against the Concrete Jungle streets or the rumbling mechanism of the subway train pulling into the station, resonating through the sprawling cityscape below. These are the soothing, rhythmic symphonies of the city, here to guide us through a day of discovery. As the breeze caresses your face and ruffles your hair atop the open-top bus or as the warmth of the bustling Metro protects you from the biting wind, you feel an indescribable sense of pleasant anticipation." /
"And providing the soundtrack to our adventure is our tour guide, a proud New Yorker. Imagine a rich, Brooklyn accent, softened by years but retaining a musical lilt that can only come from generations of family history within the city’s boroughs. Each sight, each stop, narrated with anecdotal gems from the past that make the city’s walls, streets, and landmarks come to life in an intricate tapestry of stories and memories." /
"So, get ready to journey into the heart of this legendary city. The bustle of Times Square, the majesty of the Statue of Liberty, the pulsating energy of Central Park, the architectural marvels of the skyline, and countless other treasures await our discovery. Easy conversation, laughter, and the gentle hum of city life interwoven with our own story – this is what a day in New York in fall promises. Are you ready to embark on what can only be described as an unforgettable golden adventure?" /
"As our open-top bus pauses in the heart of Central Park, our guide's lively voice comes alive over the PA system. He greets us in his warm, Brooklyn drawl, painting a vivid panorama of the park's rich history. 'Central Park,' he declares, 'is the most visited urban park in the entire United States.' And as we gaze across the undulating green expanses, dappled with fall hues, we can see why." /
"People of all walks of life meander along the paths, some jogging, some cycling, others leisurely rowing boats on the serene lake or feeding the ever-animated birds. Mothers push strollers, elderly folks tread softly along the footpaths, students sprawled on the grass engrossed in books, and little children run with ecstatic laughter, their small hands clutching colorful leaves. The scene is brimming with life, each individual wrapped in the warm embrace of this haven of tranquility amidst the city's clamor." /
"'This place has watched over us for more than 160 years,' continues our guide, his voice bubbling with familial pride. He then guides our attention to one of the park's unique features: the Literary Walk's statue of William Shakespeare. The inscription, he interprets in tones filled with awe, reads, 'There is not monument dedicated to the memory of a writer of like eminence that would insult the memory of Shakespeare. If we could build a monument high enough to reach the stars, it would be insufficient to express our high estimate of his genius; George Bancroft.' It's an awe-inspiring tribute, and it casts a contemplative silence over us." /
"From the place where we have parked, we're also near one of the park's many eateries, The Loeb Boathouse. We can smell the inviting aroma of food wafting from the restaurant, mingling with the earthy scent of the park. A few members of our tour group decide to indulge in some lakeside dining, while others unwrap their prepared picnics by the water's edge. The scene is comforting, the perfect vision of tranquility as we prepare ourselves for the next stage of our journey."

override fun Config.middle() = listOf(

)

override fun Config.end() =
"Leaving the natural beauty of Central Park behind us, we swerve eastwards on our open-top bus and soon reach one of the city's most notable landmarks, the Metropolitan Museum of Art. Our guide's Brooklyn accent rolls with a hint of pride as he announces our arrival, 'Right here folks, we've got the Met, one of the largest and finest art museums in the world.'" /
"We disembark the bus and, with our guide leading the way, head to the museum's grand entrance through an avenue lined with art enthusiasts sketching the mesmerizing architecture. The air is thick with the energy of admiration and reverence, reflecting the museum's profound zest for art and history. Inside awaits a visual feast spanning 5,000 years, housing over 2 million pieces of art, all lovingly curated from different corners of the globe." /
"Masterpieces from revered artists like Vermeer, Van Gogh, and Rembrandt call the Met home, their magnificence inspiring a palpable sense of awe among the visitors. Our guide, being well-versed in the Museum's collection, regales us with stories of each artist, their art, and the unique, captivating anecdotes behind them." /
"Every corner of the Museum breathes history and creatively, wrapping us in the warm embrace of art like nowhere else. Our guide, with a slight twinkle in his eyes, shares a beautiful literary reference about the museum from J.D. Salinger's 'The Catcher in the Rye,' illustrating its significance in the journey of self-discovery. The quote resonates with us and, in that moment, we, too, feel a part of that extraordinary tale." /
"The exploration of art inspires a hunger that is catered to by The American Wing Cafe within the Metropolitan Museum. A few of us decide to relish their artisanal sandwiches and salads, the experience enhanced by the art-filled surroundings. Meanwhile, outside in the Museum's vicinity, we observe individuals entranced by their sketchbooks, recreating the museum’s architecture. Some have ventured towards the nearby Central Park, feeding squirreling with a joy that reflects across their smile. This tranquil lunch, surrounded by the grandeur of history and art, fills us with inspiration and delight - emotions that prime us for the remainder of our captivating New York adventure." /
"As the vibrant hues of the afternoon sky slowly bleed into the gentle tones of twilight, we board our open-top bus once again, our hearts saturated with the sights and stories of the day. Beyond the city's skyscrapers, the setting sun drapes a golden cloak over New York, drenching every corner in an ethereal glow. The city, already holding an intoxicating allure, becomes almost otherworldly, sparkling under the quiet peaceful embrace of the night." /
"Our guide, with his captivating Brooklyn accent, fills us in on his favorite nighttime spots as we pass them by: the glittering marquees of the Broadway theaters, the symmetry of the architectural marvel that is the Guggenheim, and the twinkling lights dancing on the Hudson River. Every story he shares unfolds another layer of the city's multifaceted charm, revealing what it truly means to be a New Yorker." /
"Now, our journey through the bustling subway system begins. The gentle rhythm of the Metro is comforting and somehow soothing in its predictability. Murmurs of conversations fill the air, punctuated with soft laughter and endearing chatter. This all too familiar Metropolitan soundtrack is the symphony of the city, a lulling, soothing melody that weaves its own comforting tale into our New York experience." /
"As we step off the Metro and stroll down the lantern-lit streets, the feeling of camaraderie among us is palpable. We walk side by side, engaged in pleasant exchanges, sharing our best memories of the day, nipping occasionally into quaint patisseries and cozy late-night cafés, all under the soft, undulating canopy of New York nightfall." /
"Gradually, our night of gentle exploration starts to wind down. Our final stop sees us back at our starting point in the inviting glimmer of Times Square. An interplay of lights dance around, casting an illuminating glow over the mosaic of people, a testament to the vibrant essence of this extraordinary city. It is this image, the warmth of the lights, the hum of the city, and the soothing voice of our Brooklyn-bred guide, that we tuck away as the treasure of our remarkable New York journey." /
"With the city gently settling in for the night, we, too, part ways, hearts alight with the comforting memory of our day. It's an experience enriched by history, peppered with culture, and enveloped in the heartwarming hospitality of a local guide who cherishes his city with an unyielding passion. The artistry of Central Park, the whispers of time in the Metropolitan Museum, and the gentle rhythm of the city have all left an indelible mark on us. Tonight, we’ve not just toured New York; we've lived it, breathed it, and now, we gently carry the essence of this incredible city within us."
}