// this code is generated from the story file bali_2023-11-10_23-15-53.txt
    // min_stops is set to 1

    package com.downdogapp.cue

    object SleepStoryTravelShortBaliCues : SleepStoryPoseCues {

    override val start =
    "Excitement rustles through the air like a gentle breeze: the joyous anticipation of exploring the enchanting island of Bali, Indonesia, is about to unfold. The season is spring and nature is bursting into vibrant life, with the lush greenery of the tropical foliage appearing even more effulgent as flowers add their riotous colors to the scenery. As we prepare to embark on an immersive sightseeing tour, we're joined by our tour guide, a young Balinese woman whose smile mirrors the island's warm and welcoming aura. Accompanying her is a fleet of neat, brightly colored rental scooters, a common mode of transportation in Bali's serpentine paths and thus integral to our journey as we thread through bustling markets, ancient temples, soothing beaches, and sweeping rice terraces. However, the commencement of our grand adventure is signaled by the gentle hum and comfortable seat of our car as we brace ourselves to explore the spellbinding wonders of Bali." /
"Our first sightseeing spot comes into view through the car window as we approach: the renowned Ubud Monkey Forest. This sacred nature reserve and temple complex cover 27 acres of thick forest, where over 700 Balinese long-tailed monkeys scamper amid ancient trees, their eyes gleaming with untamed mischief. As we step out of the car, the driver cum guide directs us, her soft voice imbued with knowledge and reverence. The intriguing hint of a smile suggests countless shared secrets between her and these wild denizens of the forest." /
"David Attenborough’s fond quote rings true as we observe the monkeys, 'When a monkey looks into a mirror, he sees a monkey.' And as we tentatively extend our hands, offering an olive branch in the form of tiny fruits, the monkeys nimbly leap forward, accepting our peace offerings with startling dexterity. Each lively interaction becomes a cherished memory, beautifully framed by the vibrant, verdant canvas of the forest." /
"The forest, with its blend of spiritual, cultural, and natural heritage, is also home to three distinct Hindu temples constructed around 1350. Our guide leads us to these revered structures, their ancient splendor resiliently standing tall amid the bustling monkey activity, awe-inspiring symbols of the island's rich religious tapestry." /
"The temples are nestled within the undulating greenery, providing tranquil spaces for quiet contemplation amidst the lively chatter of monkeys. The soft rustle of leaves, combined with the soothing trickle of water from nearby streams, lends an aura of profound peace." /
"Stepping beyond the forest's boundaries, we find ourselves surrounded by ambient eateries serving traditional Balinese delights. As per our guide's recommendation, we order Babi Guling, Balinese roast pig. As we bite into the succulent meat, infused with the rich flavors of local Indonesian spices and herbs, it feels as if we are consuming a piece of Bali's vibrant cultural heritage, a fitting end to our visit to the anthropological and gastronomical heart of the island." /
"Taking our leave of the forest, we climb back into the car to continue our Bali adventure. The journey allows us to witness local life and delightful Balinese craft stores, our guide pointing out points of interest and sharing stories of the terrain's origins and cultural significance. We transition from the primal monkey forest to the ethereal beauty of the Tegalalang Rice Terraces." /
"The terraces hug the topography of the land, their sinuous curves forming a hypnotic, undulating pattern across the landscape. This UNESCO World Heritage Site, maintained through the traditional Subak irrigation system, serves as a testament to the Balinese's resourceful adaptation to nature. In the warm sunlight, the terraces glow, luminescent tiers of green cascading downwards, framed by tall, whispering palms above and coconut groves below." /
"The young woman driver brings the car to a gentle stop, allowing us to gaze upon the panoramic view and feel the immensity of this island's beauty. Getting out, we join locals and other travelers navigating the terraces, in rental scooters, on foot, or taking up farming tools to briefly participate in this age-old form of agriculture. We're filled with awe for the toil and effort that underpins the serenity of this moment." /
"Once we bask in the mesmerizing view, we visit a local restaurant overlooking these terraced wonders. As encouraged by our guide, we order 'nasi campur'. The vibrant flavor profiles of the mixed rice accompanied by assortments of Indonesian delicacies thrill our palates, foregrounded by the leafy wonderland that forms the backdrop for our meal." /
"Our journey through Bali's historical and natural wonders doesn't end with this soul-satisfying meal. We head towards the renowned Goa Gajah Temple, an archaeological marvel also known as the 'Elephant Cave'. It's a significant spiritual center, dating back to the 11th century. The drive to the temple is scenic, watering the seeds of anticipation of our upcoming exploration. As we approach, we spot dense forest enveloping the ancient temple, hinting at history and mystery lying ahead." /
"As we disembark from the car, the first sight to meet our eyes is the massive, dramatic face carved at the entrance, looking as if it swallows us whole, as we venture into the sacred sanctuary. The mysterious 'Elephant Cave', despite having no elephant associations, invites exploration to unravel the enigma of its nickname." /
"We marvel at the temple's beautifully carved rock-wall, explore its central meditation cavern, and witness other visitors participating in water blessings under the six waterspouts at the bathing pools. Inside the cave, the unique aura of tranquility and spirituality moves us to take a few moments of quiet reflection, echoing the site's original purpose as a meditative retreat." /
"Stepping back into the sunlight, we savor another traditional Balinese dish at a nearby warung: Nasi Goreng, Indonesian fried rice. The vibrant flavors further imprint the unique cultural experiences that Bali has to offer. As we finish our meal, the serene temple complex resonates with the echoed sounds of history and whispers of myths, soon to be discovered."

    override val middle = listOf(
    "After the enlightening and spiritual experience at Goa Gajah temple, we head towards Tegenungan Waterfall. As the car weaves through Ubud's picturesque outskirts, adorned with rice terraces and quaint village houses, our guide articulates fascinating stories and details about the waterfall. Seeing the lush landscape, we're full of eager anticipation to embrace the soothing charm of this hidden gem." /
"The journey becomes more enchanting as we swap our car for rental scooters to accommodate the terrain's narrow paths. The air grows fresher with the earthy aroma of the verdant tropics and a gratifying hint of approaching water. The rumble of the waterfall echoes like a welcoming symphony as we navigate the trail into the jungle." /
"Suddenly, the spectacular sight of Tegenungan Waterfall unfolds before us. It's an awe-inspiring cascade of about 30 meters, tumbledown amid the embrace of the tropical greenery. This specific placement, unusual due to its lowland location, imparts a unique charm to the waterfall. It's a slice of untouched paradise, hidden in the depths of the jungle, only recently touched by wandering explorers like us." /
"Adhering to Bob Ross' advice to 'let go and fall like a little waterfall', visitors are seen surrendering to the enthralling call of the waterfall, swimming in the clear pool beneath the cascade or laughing joyfully on the swing above the water. It's as if the worries of the world wash away with every splash and spray of the waterfall. Their joy is heightened by our guide's narrative about Tegenungan's magical ambiance, adding a graceful charm to the already dream-like scene." /
"After basking in the waterfall's refreshing energy, we head towards a nearby warung for a hearty meal. Balinese dishes like Nasi Campur and Ayam Betutu are served, their traditional flavors nuanced with the freshness of local produce. The Balinese dining experience, accentuated by the symphony of the waterfall in the distance and the surrounding lushness, makes for a perfect dining experience." /
"Rejuvenated and happily satiated, we set off for the Ubud Traditional Art Market. A riot of colors, the Art Market is an energetic blend of traditional Balinese culture, art, and crafts. As we stroll through the sprawling marketplace, the air buzzes with the excitement of haggling over prices and the joy of discovering perfect keepsakes among the myriad of stalls." /
"The vibraint scarves, light shirts, woven bags, and statues appear as though they've leaped out of the vibrant scenes of the movie 'Eat, Pray, Love', which partly filmed at this bustling location. Our guide narrates interesting trivia about the items for sale, each with a story weaved into its existence. We can't help but try on a pair of beautiful handmade Balinese sandals she offers us, our feet sinking into local comfort." /
"The Art Market not only soothes our shopping cravings but also delights our taste buds when we stop at a bustling warung. As we line up with eager locals and fellow tourists, our guide recommends trying the famous 'babi guling' or 'nasi campur'. The food, freshly prepared and bursting with traditional flavors, is another delicious indulgence that concludes another memorable day on our Balinese tour. The day gradually folds into the evening, promising more travel wonders waiting for us tomorrow in the enchanted land of Bali.",

"As the new day dawns, we head to our next destination: the enchanting Campuhan Ridge Walk. Our young guide steers the car expertly through narrow lanes cradled in nature's lush embrace, as vivid greens of various hues flash past our windows. Upon reaching the starting point of our walk, she points out signposts, advises on the best timings to avoid the peak tropical heat and shares insider tips about the trail - like a nature-inspired cafe called Karsa Kafe, where we could stop for refreshments while gazing upon a tranquil lotus pond." /
"Exiting the car, we feel the touch of the cool morning air and start our journey on foot along the undulating path. Campuhan Ridge Walk unravels like a natural tapestry spun with beautiful hues of green and blue. The landscape around us is a visual symphony, with the rhythm of gentle slopes, the harmony of sprawling rice fields, and the melody of a murmuring stream. Locals are seen diligently working in the rice fields, using the Subak irrigation system, their brow glistening with the kiss of the morning sun." /
"The journey becomes an interactive canvas, each scene around the bend like a vibrant painting. It inspires a soothing calmness within us, reminding us to pause and appreciate Mother Nature's masterpiece. As we stroll, our guide provides us rented scooters, adding a thrill to the overall calming ambiance. The stunning views from the mountaintop, the feeling of the fresh wind in our faces as we zip down the verdant paths, make for an unforgettable experience." /
"Our appetite for beauty is matched by our hunger for another taste of Balinese cuisine. The Babi Guling dish served in Ibu Oka, a nearby restaurant, comes highly recommended by our guide. As we dig into the succulent roast pig, we can't help but appreciate how our experiences are turning into an exquisite blend of Bali's natural and culinary treats." /
"As our meal concludes, we're ready to embark on our next expedition. Our young woman driver navigates the way to Sukawati Art Market, a place brimming with the creativity and martial prowess of the Balinese residents. As we approach the market, we're fascinated by the explosion of colors, from ornate masks and clothes to intricate sculptures and bags. Each stall showcases the soul of Balinese art, a salient feature of their life and economy." /
"The market, showcasing the world of Balinese arts and crafts, offers a kaleidoscope of items to browse through and buy. We witness the pulsating energy of haggling as vendors and customers engage in friendly price negotiations. Our guide shares stories about the traditional crafting techniques, explaining the significance of different designs based on their regional origins." /
"As we wander around the market, hunting for unique finds, we're once again treated to a local dining experience. We sit down at a food stall serving Nasi Campur, the mixed rice dish that is fast becoming our favorite. As we sample its flavors, we watch the flurry of activity around us, from fellow tourists examining trinkets to locals on rental scooters zipping by. Each moment is a slice of Balinese life, threaded together to create an exhilarating and engaging journey. Taking in the hustle and bustle, we're perfectly content, knowing there's more to explore and experience in Bali's magical realm.",

"Leaving behind the vibrant chaos and charm of Sukawati Art Market, we embark towards our next destination - the iconic Tanah Lot Temple. As we make our journey, our guide leads us onto picturesque country routes, offering views of serene rice terraces and traditional Balinese huts. Riding on rented scooters, the open air and freedom of the ride amplifies the tranquility and beauty of our surroundings, nudging us deeper into Bali's mesmerizing charm." /
"The approach to Tanah Lot, perched atop an offshore rock amidst the gentle lapping waves, is a vision that takes our breath away. Steeped in mythology and endowed with the spiritual energy that marks Bali, Tanah Lot stands as a relic of balance and faith, its silhouette enhanced by the glorious hues of the setting sun. As we near the temple, our guide shares the story of the Javanese priest Dang Hyang Nirartha, who created this sacred space to pay tribute to the sea god, Baruna. Through her storytelling, these ancient stones are imbued with life and whispers of the past." /
"When the tide recedes, we take the opportunity to cross the seaweed-strewn path to the main temple. While strict rules prevent us from entering the temple grounds, around us, the ritualistic traditions of Bali unfold. Visitors partake in purification ceremonies, their silent prayers merge with the soft rhythm of the ocean waves, and the Holy Snake - the temple's mystique - is whispered about with reverence. Meanwhile, the spectacle of breathtaking panoramas dotted with various poses of fellow travelers against the magnificent backdrop paints a lively tableau." /
"As the sun dips lower, painting the sky in golden hues, we head to a local eatery near Tanah Lot. Once again, Babi Guling, the traditional Balinese dish made from suckling pig, sits proudly on our table. As we relish the delectable preparation, the view of the silhouetted temple against the sunset sky adds a magical quality to our meal." /
"Our next destination is the majestic Gunung Kawi Temple - another jewel in Bali's spiritual crown. Through beautiful landscapes and calming rice terraces, our guide drives us to Tampaksiring, the home of this ancient monument. Sharing the history and folklore affiliated with the temple, she lets us in on the cultural and ancestral significance of this 11th-century marvel." /
"As the temple's grandeur unfolds before us, we're greeted by ten impressive rock-cut shrines, or candis, etched into the wall of a cliff. These monumental structures with the serenity of the holy spring found within the temple complex urge us to partake in special ceremonial blessings." /
"Watching other visitors meditating, making offerings, or immersing themselves in spiritual rituals is a captivating experience, further deepening our understanding and appreciation for Balinese spirituality and culture. We end our visit with Bebek Betutu at a local eatery; the slow-cooked, spice-marinated duck dish fills us with warmth, rounding off a day steeped in history, spirituality, and rich Balinese flavors. As we make our way back to our vehicle, we carry a sense of fulfillment and anticipation for the next leg of our journey through Bali's captivating heartland."
    )

    override val end =
    "As sunrise greets the beautiful island of Bali, painting the sky in splendid pastels, we embark on our journey towards our first destination of the day - the Pondok Pekak Library and Learning Center. Situated in the heart of Ubud, the Center bears testament to the traditional arts and literature of Bali. Within its quiet walls reside over 30,000 books, a treasure trove of knowledge awaiting our eager explorations. As soon as we disembark from the car, our guide's excited whispers fill the air, elaborating the significance of the place and the dance workshops that promote the colorful fabric of Bali's culture." /
"The ambiance within the library is a related hum of enthusiastic learning and local conversation. Tourists and locals sit side by side, sharing experiences, lost in the world of written words, or deeply engaged in traditional arts lessons. A sense of unity weaves through the room as everyone shares their love for learning and cultural appreciation. We find a kinship in this camaraderie, immersing ourselves in a Kawi script workshop, a rare experience painted with the essence of Balinese heritage." /
"Beyond the library, a lush garden blooms in serene silence, inviting us to sit and enjoy a quiet moment. As we soak in the peaceful surroundings, the harmonious hum of language and music workshops playing in the background paints a beautiful endnote to our library visit." /
"Before long, we're back on the road, directed by our guide towards our next destination - Sanur Beach. However, first, she recommends a nearby restaurant where we can satiate our appetites. A local dish, Nasi Campur Bali, graces our lunch table, as we savor the variety of flavors and textures dancing on our palates." /
"Nourished and content, we make our way on rented scooters to the stunning Sanur Beach. Our guide leads the scooter convoy as we breeze through the local streets. Upon arrival, its gentle waves, caressing the golden sand, offer a warm welcome. The beach is not just a natural paradise but also a historical landmark, hosting Bali's first major hotel and being an important pivot in Bali's introduction to global tourism." /
"As we walk down the famed Jl. Danau Tamblingan road, local shops and charming warungs dot our path. The scent of the sea draws us closer to the coastline, where the breathtaking sunrise awaits. Our guide omits details of the stone pillar in Blanjong, adding to the beach's stories amongst other legends right before the unmarked beginning of the day." /
"The sunrise, casting a magical glow over the calm sea, is a sight to behold. The horizon erupts in a symphony of colors, turning the moment into an exhilarating start to a new day. Our guide's soothing voice narrates the local belief about welcoming the sunrise as a symbol of new beginnings, enhancing our admiration for Bali's spiritual undertones." /
"As we stroll across the coast, the paved path guides us through beachfront cafes and warungs. We are not just mere spectators but active participants - walking leisurely, snacking on local delicacies, capturing the aesthetics of our surroundings through our lenses, creating irreplaceable memories around this fabled expanse of sand. With each new dawn, Bali continues to unveil its cultural treasures and natural splendors, revealing why it's known as the 'Island of the Gods'." /
"Our sightseeing tour carries us on a current of exploration and spiritual enrichment, our memories brimming with Bali's diverse locales and tales. Today, we embrace the anticipation of another adventure beautifully woven through the narrative of our journey. Our young, local guide sets the tone, her resplendent smile playing a homely refrain to the unfolding symphony of Bali's rich culture." /
"Winding our way amidst lush landscapes, we journey towards one of Bali's age-old marvels - the Pura Tirta Empul Temple. As the scenic tableau unfurls around us, our guide elaborates the spiritual significance of the towering pagoda-like shrines, or 'pelinggih meru', we spot along the way, masterfully sketching a vivid image of the sanctuary we're yet to visit. The aroma of incense whispers an ethereal welcome even before we exchange our car for rental scooters, enabling us to connect more intimately with the serene environment." /
"As we reach the heart of the temple, a sense of spiritual tranquility envelops us. Pura Tirta Empul is a quintessential part of Bali's fabric, traditionally serving as a stage for the religious ceremonies of the Hindu community. Built in 962 A.D during the Warmadewa Dynasty, the temple's grandeur is accentuated with its primary deity, Lord Vishnu, and the mythical 'Tirta Empul', or 'holy water spring', it houses." /
"Surrounded by native Balinese people bedecked in colorful and artistically layered traditional attire engaged in prayer, we experience the respectful solemnity attached to this place. The soothing gurgle of spring water, the scent of flowers in the offerings, the serene hum of hushed chants, paints a spiritual panorama that soothes the soul and imparts a newfound respect for Balinese tradition." /
"Immersion in this world of spirituality extends to participating in the ritual of cleansing ourselves in the holy spring. Each droplet of water that ripples from the spring and drips off us carries a sense of purification, casting a calm, restful ambiance over the proceedings. As the water cleanses our body, it seems to take with it the distractions of the physical world, leaving behind a serene clarity." /
"After this deeply emotive experience, our appetites lead us on, and we are guided to sample a traditional Balinese dish - the savory Bebek Betutu. The slow-cooked duck, richly marinated in spiced herbs, melts smoothly in our mouths, every bite an exquisite blend of flavors and nostalgia." /
"With the day drawing to a close, we take a final stroll around the temple, admiring the resident natives selling spiritual charms and handicrafts in the local market. As the sun dips behind the temple, shadowing the grandeur of the pagodas against the darkening sky, we bid our adieus to the serene solitude of Pura Tirta Empul." /
"As our journey through Bali unfurls, every day uncovers another layer of its timeless beauty and spiritual tranquility. Captivated by the symphony of the natural and cultural wonder that Bali weaves, we carry in our hearts an imprint of this magical land's soul. Despite the countless miles we've traveled, our Bali pilgrimage feels as if it's just begun, the allure of the unseen stirring a thirst for more captivating experiences to come. For now, as the luminosity of the stars illuminates our path, we are left embracing warm memories and eagerly anticipating the continuing saga of our Balinese journey."
    }