// this code is generated from the story file kyoto_2023-11-10_00-41-50.txt
    // min_stops is set to 1

    package com.downdogapp.cue

    object SleepStoryTravelKyotoCues : SleepPoseCues {

    override fun Config.start() =
    "In the heart of Japan, nestled amidst verdant hills and serene rivers, lies the ancient city of Kyoto. As cherry blossom petals cascade gently down in the soft spring breeze, the city is transformed into a picturesque scene straight from a painting. The season adds a poetic touch to the landscape, unfurling a carpet of soft pink and white. Eagerly, we await the captivating journey that lies ahead in this city, where traditional grandeur meets modern elegance effortlessly." /
"Our mode of transportation during our time here is just as enchanting as the city itself. Rickshaws, the two-wheeled, man-powered vehicles guided by jovial middle-aged men, are a charming throwback to a simpler time. Our rickshaw driver is a cheerful man, brimming with countless fascinating tales about this storied city. But we won't stay in the rickshaw the entire time -- we'll also get to explore on our own two-wheeled rides, bicycles, on which we can gently slice through the cool city air and take in the peaceful landscape at our own leisurely pace." /
"While we're not cycling, we might also meander through the city by foot, strolling under the blooming cherry blossom trees, crossing stone bridges over tranquil streams, and losing ourselves in the labyrinthine beauty of Kyoto's winding back streets." /
"Immersing ourselves in Kyoto isn’t just about seeing. It’s about feeling, experiencing and connecting with a remarkable culture that cherishes its past as it strides into the future. Our journey has not yet begun, but we can already feel the anticipation bubbling up within us, the promise of gentle adventures and warm connections lays ahead, as we prepare to uncover each layer of this dramatic city, one sight at a time." /
"Pulling ourselves through the streets of Kyoto, our rickshaw driver skillfully maneuvers the traditional Japanese transport, our first destination is Kinkaku-ji, the iconic Golden Pavilion. As we approach, a glimmering structure unfolds before our eyes, its two top floors coated in gleaming gold leaf, mirroring the sunlight in a devouring dance." /
"Steeped in history and serenity, this Zen temple's golden hue is even more remarkable against the backdrop of the azure sky. We listen, as our guide tells the tale of how this architectural wonder was once a retirement villa for a revered shogun, Ashikaga Yoshimitsu, in the late 14th century. He embellishes his narrative with stories of the temple's unfortunate fate, burned down by a novice monk in the mid-20th century, a tale that also inspired Mishima Yukio's novel, 'The Temple of the Golden Pavilion.'" /
"A thrill of anticipation runs through us as we leave the rickshaw, setting foot on temple grounds with an air of reverence. The atmosphere brims with a soothing tranquility, prompting some visitors to engage in quiet contemplation or meditative practices. We join others in admiring the temple's intricate architecture, its true beauty magnified against the backdrop of a carefully cultivated garden sprinkled with the vibrancy of spring blossoms." /
"Our senses are further enticed by a waft of rich aroma from the nearby Sekkatei Teahouse. As if by magnetic pull, we're guided towards it, finding ourselves seated comfortably on tatami mats and served with a bowl of frothy matcha tea, whose bitter notes provide a delightful contrast to our sweet Japanese treats. The fading taste of matcha on our tongues, we hop onto our bicycles, eager to explore the undulating, narrow streets of the surrounding traditional neighborhood, relishing the comfortable quiet and gentle beauty of Kyoto as it unravels before us."

    override fun Config.middle() = listOf(
    "Leaving the tranquil grounds of Kinkaku-ji and its calming aura behind, our rickshaw guide leads us towards the boisterous hum of Nishiki Market. The transition is invigorating, the quiet of the temple replaced by the bustling energy of what's famously known as 'Kyoto's Kitchen.' Over 130 family-run food stands and shops line the narrow streets, offering an array of local gastronomic delights, their bright, captivating colors adding to the market's vibrant character." /
"Navigating through this thriving maze, our guide introduces us to the unique delights that are quintessentially Kyoto. From skewered octopus with quail egg to Kyoto-style pickled vegetables, the symphony of flavors captivate our tastebuds, each dish more deliciously satisfying than the last. We also taste yuba, tofu skin that epitomizes the simplicity and delicate flavors of Japanese cuisine." /
"Our trusty guide explains the cultural significance of the market and its culinary offerings, reinforcing the saying that 'there's no dish that doesn't include something from Nishiki.' His shared memories about the market and his favorite stalls imbue a personal touch to our own experience as we listen, each story and smile pulling us deeper into the local culture." /
"Touched by the guide’s embodied passion for this culinary haven, we indulge in the human connections forged in the market. He warmly introduces us to the vendors, instructing us on the etiquette of asking for food samples in Japanese, transforming this experience into a language lesson as well." /
"When the rickshaw ride is over, we mount our bicycles to engage with the market on a more personal level, weaving our own paths through the labyrinthine market. This second visit allows us to savor the delightful sensory assault once more, revisit our favorite stops from the tour with our guide, discover new favorites on our own, and further immerse ourselves in the pulsating heart of Kyoto's cuisine and culture. The rhythm of the wheels against the cobblestones, the inviting aroma wafting in the air, the laughter and chatter rippling through the market, all of these elements draw us into a beautiful rhythm that is uniquely Kyoto's own.",

"Bidding farewell to the delightful Nishiki Market, we continue our journey. Our rickshaw driver guides us, his wheels tracing the well-worn path towards the captivating Ginkaku-ji, or the Silver Pavilion." /
"Originally intended to be cloaked in silver as a tribute to the golden Kinkaku-ji, our guide explains that the Silver Pavilion was never completed as planned. Rather, it acquired its name from the ethereal shimmering effect moonlight cast onto its darkened exterior. A masterpiece in its own right, the temple remains an unfinished beauty, established in 1482 by shōgun Ashikaga Yoshimasa, who envisioned an artistic haven immersed in nature's embrace." /
"Stepping off our rickshaw, we're led into a setting that feels as if it captures the very essence of tranquility. Ginkaku-ji is a testament to the Higashiyama culture of the Muromachi period, displaying harmonious interweaving of art and nature." /
"We are introduced to the enchanting dry-sand garden known as the 'Sea of Silver Sand.' Immaculately manipulated, the sea segues into the visually captivating 'Moon Viewing Platform,' a large sand mound that looks like a fallen piece of the moon, nestled within the garden's silvery sands. Our guide's voice softens as he narrates tales of Yoshimasa, moon gazing from the platform, finding sublime tranquility in the midst of the sand sea." /
"Afterwards, we retire to a traditional tea house within the temple grounds. The weather cooperates, allowing us a serene experience within the shadow of the Silver Pavilion. We sip on pleasantly bitter matcha tea, the quiet rustle of leaves whispering tranquility into the air." /
"The beauty of the moss garden has its own silent call. Calmly, we wander its winding paths, occasionally crossing paths with other visitors lost in their thoughts. Some of us might find a quiet bench and sit, watching koi fish dance carelessly through the clear water of a pond." /
"On our bicycles, we explore further, the soft sounds of our wheels crunching against gravel the only noise disturbing the peaceful silence. We navigate through the gardens independently, feeling the quiet hum of nature lull us into soothing tranquility. In this sacred space, the world seems to slow down, and we bask in the mindful enchantment of Kyoto’s Ginkaku-ji.",

"As we extricate ourselves from the soothing embrace of the Silver Pavilion, we are once again in the hands of our jovial rickshaw puller, who now steers us towards the expansive Kyoto Imperial Palace Gardens. The park is a place of tranquil repose and natural beauty, once the home to the families of the Imperial court. This historical park teems with the elegance of a bygone era, its spacious lawns dotted with historic buildings that echo tales of the past." /
"Our rickshaw ride slowly transforms into an immersive journey through the lush landscape that unfurls in unimaginable beauty, vibrant in the spring air, with bursts of vivid colors from the cherry blossom trees. Our guide matches the splendor of the park with riveting stories of the palace grounds and the lives of the Imperial court." /
"We disembark from the rickshaw, feeling a profound connection to these stunning surroundings. Given the chance, we seize upon a traditional Japanese tea ceremony at one of the garden's tea houses. With a cup of matcha tea warming our hands and the sweet taste of wagashi delighting our palates, we appreciate the meticulous art of this ceremonial tradition and the interplay between culture and nature." /
"On foot, we amble along the garden paths, observing visitors who have chosen picturesque spots for picnicking under the trees or practicing calligraphy by the gentle lapping waters of the palace's canals. The serene aura lends a peaceful rhythm to everything around, creating a harmonious blend of man and nature, past and present." /
"When it's time, we mount our bicycles, ready to explore the adjoining park at our own pace. This intimate journey opens us up to the quieter aspects of the gardens - the gentle rustle of wildlife hidden amongst the foliage, the subtle, soothing fragrance of the blossoming trees, and the delicate whisperings of the wind among the leaves. In this refined tranquillity, we find ourselves increasingly attuned to the quiet elegance that characterizes this historical city, feeling the persistent heartbeat of nature and history that resounds through the Kyoto Imperial Palace Gardens.",

"The crisp air of spring takes on an excited quality as we cycle towards our next stop, the Kyoto Railway Museum. This monument to transportation grandeur traces the evolution of Japanese rail technology through impressively real-size exhibits. The quiet hum of the rickshaw and the soft whirring of our bicycle wheels seek to mimic the much grander sounds we are about to encounter." /
"Our guide’s stories come to life as we admire more than 50 retired train cars and locomotives on display. The star of the show is the Steam Locomotive #230. Built in 1903, it maintains its historic dignity as the oldest existing locomotive in Japan." /
"The museum, which started as the Umekoji Steam Locomotive Museum and was expanded in 2016, offers interactive experiences that transport us into the driver's cab. We delight in the chance to control a railway diorama, one of the largest in Japan, via a simulator, chugging along imaginary paths drawn by Japanese steam power." /
"A poignant passage from 'The Great Passage' by Shion Miura comes to mind as we stroll among the exhibits—a romanticized depiction of train travel in Japan, where journeys signify farewells and new beginnings." /
"By the time hunger strikes, we are delighted to discover a unique dining option—a restaurant set in a remodeled dining car. Here, we savour our ekiben, a boxed lunch teeming with rice, fish, pickles, and other local delicacies, each bite a celebration of Kyoto’s diverse culinary culture." /
"Pedaling onwards, we admire how fellow visitors engage with the museum, posing for keepsake photos in front of the antique locomotives or losing themselves to the virtual reality of the train simulators. Juxtaposed with the tranquil Kyoto Imperial Palace Gardens, the Kyoto Railway Museum is a din of delightful discovery, as we cycle gently under the charming canopy of cherry blossom trees nearby, our hearts filled with the warm glow of Kyoto's rich history.",

"Leaving behind the enamoring tales of the railway era, we traverse paths overhung by cherry blossoms and flanked by a calming canal. We are heading towards the philosophical jewel nestled amidst Kyoto's verdant enclaves - Nanzen-ji Temple. The bicycle ride, a soothing serenade of soft sounds from our whirring wheels and gentle flowing water, brings us closer to the Zen heart of Kyoto." /
"As we enter the temple complex, our eyes are drawn to the grandeur of the monumental Sanmon gate. Our jovial guide, imbuing history with familiar warmth, tells us about its symbolism — a gateway to enlightened Nirvana. His voice wavers with reverence as he recounts the narrative of Emperor Kameyama, who transformed his villa into this Zen temple in 1291." /
"The Hōjō, the former head priest's residence, becomes a source of shared intrigue. Our eyes take in the mysterious beauty of its screen paintings and iconic rock garden, appreciated as a national treasure. Remembering the references to Nanzen-ji in classical Japanese literature, such as 'The Tale of Genji,' we appreciate our privileged access to a site of words made tangible." /
"Among the Zen tranquillity, a surprising landmark catches our attention — an aqueduct, part of the Lake Biwa Canal. Its imposing structure, a stark contrast against the Zen's architectural simplicity, represents the embodying blend of Japan's timeless traditions and its relentless march towards progress." /
"Venturing inwards, we allow ourselves to sample a taste of Zen aesthetics. Comfortably seated within Nanzen-ji’s sub-temple, Tenjuan's garden, we take in the seasonal visuals as we sip our matcha tea. Each sip brings a sense of serenity, matching the surrounding tranquility." /
"Engulfed in the divine calm, others around us lose themselves in Zen meditation or photography, often pausing to capture the mesmerizing design of the stone garden. Following their gaze, we find ourselves lost in the dance of the light and shadow playing off the temple's unique architecture and the magnificent view of Kyoto unfolding below." /
"The culinary ethos of Nanzen-ji brings us to the delicate flavors of tofu cuisine. Seated in one of the temple's calm eating spots, we savor the exquisite Yudofu (hot tofu) and Yuba (tofu skin) dishes— both an embodiment of Buddhist simplicity and Kyoto's culinary heritage. Every bite, like every view and every story shared, adds to our rich tapestry of experiences in Kyoto.",

"As day gradually tips into evening, we embark on a new chapter of our Kyoto exploration. Our friendly rickshaw driver escorts us to Pontocho Alley, a historic district that has been flourishing since the 16th Century. The narrow alleyway, hemmed in by traditional tea houses and restaurants, hums its lullaby, suffusing the air with a sense of life that has flowed through this place for centuries." /
"Cobbled streets underfoot reverberate with echoing tales of geisha that our guide artfully narrates. He tells of their grace, their artistry, their integral part in the history of this lantern-lit alley. As he speaks, we catch glimpses of modern-day dialogue with Pontocho's past – fellow sightseers easing into traditional tea houses or eateries accompanied by these exquisite entertainers, the rustle of their kimono whispering tales of old Kyoto." /
"The rickshaw tour is an undulating wave of old-world charm and serene views of the Kamogawa river; a gentle breeze carries the sound of running water, playing a soothing underscore to our guide's enthusiastic tales. With every twist and turn through the alley, we're drawn into the embracing arms of living history, playing out within these age-old walls." /
"Later, as we straddle our bicycles, we map our route across the maze of Pontocho, thus making way for a more personalized immersion. We may find ourselves enchanted by a quiet exchange between a bird and a butterfly, a curious ballet amidst the steady thrum of this bustling dining area, offering a snapshot of the harmonious balance between Kyoto's natural beauty and its urban pulse." /
"A sudden waft of enticing aromas diverts our attention to the array of restaurants lining the alley. Many promise traditional kaiseki dining, an intricate, multi-course Japanese meal that celebrates the varied flavors of this city’s culinary tradition. The inviting smell of simmering broth, fresh vegetables and waves of umami paint mouthwatering images of these delicacies, adding yet another layer to our sensory tapestry of Kyoto memories. As we continue our meandering ride through Pontocho Alley, we relish each moment, savoring the intoxicating blend of tradition, tranquility, and tantalizing tastes that define this ever-evolving cityscape.",

"Our rickshaw rolls on, leaving behind the buzzing life of Pontocho Alley to introduce us to the serene grandeur of the Heian Shrine. As we approach, the magnificent red entrance gate announces the distinctive presence of a site touched by the divine. The sacred air surrounding the shrine, established to honor the spirits of the first and last emperors who resided in Kyoto, imbues the surroundings with a sense of reverence." /
"Our guide tells us of the shrine's origins, how it was raised in 1895 to mark eleven centuries since Kyoto became the capital. As we take in the architectural marvel representing a 5/8 scale model of the ancient imperial palace, he captivates us with stories of Emperor Kammu and Emperor Komei – their reigns bookmarking the rise and fall of Kyoto as Japan's capital. Their stories elicit the old Japanese saying in our guide's rendition, 'All's well that ends well.'" /
"Stepping off the rickshaw, we follow our guide into sprawling gardens that breathe life into the shrine's tranquil ambiance. Depending on the season, cherry blossoms may shower soft petals upon us or vibrant autumn leaves might carpet our path. We watch as others participate in Shinto rituals — making offerings or ringing prayer bells, their movements slow and deliberate in the hushed serenity of the shrine." /
"Drawn by the allure of experiencing a tea ceremony, guided by the soft chatter of others, we gravitate towards the garden tea house. In this tranquil setting, we partake in the ritual, savoring the bitter-sweet harmony of matcha tea and traditional sweets, the experience infusing the day with a calm rhythm and deep respect for tradition." /
"Our return visit, this time on bicycles, occurs in quieter strokes. We pedal our way back to the shrine, choosing to spend some time by a serene pond filled with lazily drifting turtles. Here, amidst the tranquility of our surroundings, we find space for quiet contemplation and appreciation, letting the spiritual undertones of the Heian Shrine wash over us, as we rest, reflecting on the moments that define our Kyoto journey.",

"Leaving the peace of Heian Shrine behind, we find ourselves transitioning to the vibrant energy of Teramachi Street, a bustling covered shopping street. Our rickshaw rolls smoothly onto this lively boulevard, teeming with an eclectic array of shops. Our jovial guide points out how the street, steeped in middle-age history, has transformed from a temple district to one of Kyoto's exciting shopping destinations, a 'Temple Town' woven into modern city life." /
"As we glide through the market, the guide's voracious storytelling paints a vibrant picture, bringing the folk tales and old legends associated with the street to life. Every turn becomes an opening verse to a new tale – a family-run craft shop here, a generations-old sushi stall there – each contributing towards the grand narrative that is Teramachi Street." /
"We leave the comfortable rickshaw to start experiencing the street on foot. We meander through a labyrinth of stores that sell everything from stylish fashion to traditional Kyoto crafts. Our guide recommends us to Shogado, a bookstore specializing in beautiful Japanese stationery and art materials, where we find ourselves delighting in the assortment of delicate papers and intricate ink patterns." /
"Further down the street, the aromatic blend of matcha and traditional sweets like mochi draws us into a congenially crowded café. We enjoy moments of respite, savoring the tea and sweets, watching as the shoppers roam from store to store, engaged in 'omiyage' shopping, selecting gifts embodying the essence of Kyoto to take back home." /
"Later, on our bicycles, we navigate the thrumming energies of Teramachi Street at our own pace. We stop occasionally to investigate promising storefronts, occasionally snacking on mouthwatering street food that abounds. As the day unfolds, we find ourselves absorbing the layers of culture, tradition, and modernity that have interwoven to create the vibrant tapestry of life on Teramachi Street.",

"Our guide directs the rickshaw towards a place of quiet reverence away from the lively streets – the serene Philosopher's Path. This charming walkway traced along a peaceful canal was once the daily route of the famed Japanese philosopher, Nishida Kitaro. As we traverse the path, our guide, his voice imbued with a measured respect, shares anecdotes about the contemplative walks Nishida would undertake here, immersing himself in thought and observation." /
"The winding path, enclosed by hundreds of elegantly drooping cherry trees, provides a feast for the senses, particularly during the sakura season. Making this a favored spot for Hanami, the centuries-old tradition of cherry blossom viewing in spring. Our surroundings come alive with the stunning spectacle of cherry blossoms in full bloom, a shower of pink and white petals creating a dreamlike canopy under the sky." /
"Incidentally, we pause to reflect on a quote by Nishida himself, shared by our guide - 'An intellectual is a person who creates a subjective world and objectifies it.' Amidst the gentle showers of cherry blossom petals softly falling into the flowing canal, we seem to understand Nishida's wisdom from a more profound vantage, his philosophy mirrored in the delicate dance of the petals." /
"Along the path, we indulge in soft, warm yudofu served in a quaint restaurant, the tranquil surroundings amplifying the subtly nuanced flavors of the tofu hot pot. We couple our meal with a comforting serving of matcha green tea, its frothy warmth creating a blissful counterpoint to the cool breeze sweeping over the path." /
"Tearing ourselves away from the inviting rickshaw, we embrace the unmatched freedom of our bicycles, reexamining the Philosopher's Path from our intimate perspective. As we gently cycle along, other visitors echo our awe and share our peace, capturing the picturesque serenity with their cameras or quietly walking the path, each person a part of the moving tableau of life alongside the canal. Under the delicate veil of drifting cherry blossom petals, we realize that in our quest to understand Kyoto's heart, we have become philosophers ourselves, contemplating the unfolding beauty that surrounds us.",

"Leaving behind the tranquil canal of the Philosopher's Path, our enthusiastic rickshaw driver moves us towards another historic marvel in Kyoto's cultural landscape - the Sanjusangen-do Temple. As we approach, he regales us with the origins of the temple's name, 'hall with thirty-three spaces between columns,' a nod to its unique architectural design." /
"Standing before the longest wooden structure in Japan, we are met with a sight of unrivaled magnificence - the temple houses not only a central statue of Kannon, the goddess of mercy, but also a thousand life-sized statues of the same deity, each intricately crafted and a sight to behold. This grand assemblage, flanked by twenty-eight statues of guardian deities, compels a collective gasp, its sheer scale enveloping our senses." /
"Our guide delves into tales from the temple's history, spinning stories of its founder, Taira-no-Kiyomori, a figure of prominence from the late Heian period, and the annual Toshiya archery contest, an event dating back to the Edo period. His narration further enhances the experience, weaving threads of cultural context into our exploration of the temple." /
"A reminiscent smile graces our guide's face as he relates a literary reference to Sanjusangen-do Temple. He cites Jun'ichirō Tanizaki's novel 'The Makioka Sisters' (Sasameyuki), where the characters grace the temple for the Toshiya ritual. As he shares this snippet of cultural interplay, the scene from the novel vividly blossoms in our imagination." /
"Stepping inside the temple, we are imbued with a respectful silence, following the unspoken rule against photography. We admire, contemplate, and pay respects, joining others in witnessing the sea of statues, our hearts resonating with the energy of a thousand Kannon blessings." /
"Post our temple visit, the inviting smell of yudofu from nearby restaurants tempts us to relish another serving of this classic Kyoto dish, the comforting warmth of the tofu harmonizing with the sense of spiritual tranquility we've just experienced." /
"Leaving the bustling temple behind, we take to our bicycles for a leisurely ride through the quiet traditional neighborhood surrounding the temple. We stop by the picturesque Horikawa Canal, grateful for the serenity it offers. Embraced by the gentle spring breeze and mesmerized by the cherry blossoms cascading down in a surreal spectacle, we soak in the gentle ambiance of Kyoto’s spiritual tranquillity at Sanjusangen-do Temple.",

"Our rickshaw ride now leads us to the otherworldly embrace of another iconic Kyoto spectacle, the Arashiyama Bamboo Grove. As we arrive, we find ourselves entering a different realm, one where a sea of towering bamboo stalks reach for the skies, their slender bodies bending and swaying in a soothing rhythm, a dance choreographed by the wind." /
"The grove, renowned for centuries, pulsates with an indescribable mystic energy. Our happy confidante of a tour guide breaks into an enchanting narration, his voice blending seamlessly with the whispering melody of the bamboo leaves. He tells us of the place's long-standing fame and the names it has earned from its ethereal charm - 'the walking path of enlightenment' and 'the bent sea of green'." /
"We take a moment to silently reverence the Nonomiya Shrine nestled within the grove's heart - an institution of importance dating back to the 11th century, and significantly mentioned in 'The Tale of Genji'. Its rich cultural footprint adds deeper resonance to this sea of tranquillity." /
"At the entrance of the grove, our attention is courted by the rhythmic thuds of a small family-owned mochitsuki shop. There, amidst the mesmerizing bamboos, the family continues the legacy of mochi-making. The spectacle of glutinous rice being pounded into delectably soft mochi draws us towards it." /
"Our senses overwhelmed by the magical allure of the grove and the mouthwatering anticipation invoked by the mochi-making, we perch on our bicycles to explore Arashiyama at our own pace. As we follow winding paths leading deeper into the verdant surroundings, we cross paths with fellow explorers - photographers capturing the grove's beauty, locals practicing Tai Chi in sync with nature, all bound by the shared tranquillity of the bamboo grove." /
"Each random turn we make on our bicycle adventure rewards us with an unseen spectacle, maybe an intimate viewing spot of the grove or a quaint local cafe. Assuming our spot amid a stream of locals and tourists, we bask in an unforgettable Arashiyama experience, savoring matcha tea and sweets further infusing our day with Kyoto's flavorful complexity. Amidst the towering bamboos, we understand what it means to be lost and found simultaneously, every gentle sway of the bamboo strengthening our connection to Kyoto's magical charm.",

"We bid farewell to the enigmatic embrace of the Arashiyama Bamboo Grove and embark on a rickshaw ride to Maruyama Park, the grandest city-center park in Kyoto. Drawing a myriad of nature lovers to its grounds every year, especially during the cherry blossom season, the park exudes an enchanting allure that has withstood the test of time." /
"The highlight of the park, as recounted by our jovial guide, is undoubtedly the large weeping cherry tree – the shidarezakura. Its branches, heavy with bountiful blossoms, create a riot of effervescent pink against the clear spring sky, a sight that is rendered even more enchanting when it is tenderly lit at night." /
"As we navigate through the park, our guide leads us to the statue of samurai Shinsaku Takasugi, a monument to the man who played a crucial role in overthrowing the Tokugawa Shogunate during the Meiji Restoration. While it stands in silent homage, our guide's narrative breathes life into Takasugi's historical tale." /
"We round off our rickshaw tour with a delightful culinary indulgence, diving into the crispy-on-the-outside, soft-on-the-inside takoyaki, followed by sweet mochi infused with seasonal flavors— a taste that seems to embody the delightful merging of the urban and natural charms of Kyoto." /
"As we part ways with our guide and continue exploring the park on our bicycles, we take in the tranquil river of hanami-goers alongside us, each visibly captivated by the blossoming cherry trees overhead. Families gather for picnics under the delicate shade of these blossoms, laughter and joy blend with the whispering sway of the cherry trees and the murmuring flow of the nearby canal." /
"Wandering through the dappled paths, the fragrance of blooming flowers fills our lungs, the soft rustle of our bicycle wheels on the leaf-carpeted trails plays a natural symphony, and the spectacle of blooming cherry blossoms grace our hearts with a tranquil joy unique to springtime in Maruyama Park. With every pedal stroke, we are soaked in the serene harmony of city elegance and natural splendor that is quintessentially Kyoto.",

"Leaving the tranquillity of Maruyama Park in our wake, we venture towards the dynamic world of the Kyoto International Manga Museum. Our dependable rickshaw driver navigates the streets with ease, transporting us into the heart of Japan's iconic manga culture." /
"As we approach, we catch sight of fascinating manga characters splashed across the outer walls of the former Tatsuike Elementary School, their lively presence signaling the treasure trove of Japanese comics that lies within. Our guide's enthusiasm bubbles over as he shares captivating stories of manga's history, its impact on Japanese society and culture becoming more tangible as we delve deeper into the museum." /
"On display are approximately three hundred thousand manga pieces, their resilient pages bearing tales from different eras. The 'Wall of Manga,' an extensive collection of comics from 1945 to the present day, stands as a testament to the profound evolution and diversity of the art form." /
"Wandering amidst the vast collection, we come across carefully preserved, out-of-print manga, cherished relics from the Meiji period, and rental books from the postwar era — each a slice of cultural memory imprinted with ink." /
"With a chosen manga book in hand, we escape into the museum's outdoor garden, enveloped by the warmth of a sunny afternoon. Sinking into the line-drawn narratives amid the soothing rustle of pages, we become part of the tableau of visitors immersed in their chosen tales under the open sky." /
"Later, we find a corner in the museum café, savoring the earthy flavor of matcha tea and the subtle sweetness of wagashi. The vibrant manga artwork around us adds a splash of color to our culinary indulgence, encapsulating us further into the mesmerizing manga universe." /
"We conclude our visit on our bicycles, navigating the museum's surroundings, the colorful manga characters on the walls bidding us farewell. As we pedal away, each stroke allows us to appreciate the interplay of contrasting energies – the serene harmony of Maruyama Park and the dynamic vibrance of the Manga Museum – harmonizing into the immersive symphony that defines our Kyoto journey.",

"Resurfacing from the brilliant world of manga, our journey continues as we traverse Kyoto's maze of wonder towards the cherished Tenryu-ji Temple. A part of the revered UNESCO World Heritage Sites, the temple comes highly recommended for its alluring garden and scenic views of Arashiyama Mountain." /
"As we enter the ancient Zen temple, established in 1339, an overflow of tranquility greets us. Our jovial rickshaw guide breaths life into the 'Temple of the Heavenly Dragon,' narrating captivating tales about its past and the revered garden designer, Muso Soseki. As he guides us along the manicured paths, his enlightened storytelling adds layers of meaning to the site's profound environment." /
"One sight that leaves an indelible imprint on our minds is the Sōgen Pond. This 14th-century relic holds its original form, a testament to the enduring legacy of Kyoto's past. Bordered by lush landscaping, the pond adds a calming element to the temple's grand architecture." /
"Our guide's animated narration briefly references a famous picture book, 'The Temple of the Golden Pavilion,' deepening our appreciation for Japan's rich literary history embedded not only in books but also within the walls of these age-old structures." /
"Leaving the temple, we transition once again from one cultural treasure to another, indulging in a traditional yudofu meal at a nearby restaurant. The warm, soft tofu simmering in hot water is an emblematic dish of the region and offers us a culinary closure to our temple visit." /
"Mounted on our bicycles, we journey toward the nearby Arashiyama Bamboo Grove. The towering bamboo stalks stand guard along our path, their whispers carrying faint echoes of our jolly guide's laughter and tales. Many of us pause along the Hozu river bank, taking in the panoramic view of the famous Togetsukyo Bridge or engaging in picnic lunches, enriching our experience." /
"Despite the gentle hustle of other visitors, the tranquillity within Tenryu-ji Temple's grounds remains undisturbed, serving as a collective meditation space where each of us connects with the serene beauty of Kyoto, drawing our own enlightenment from the past nestled in the present.",

"Retracing our steps through the bamboo grove and back to the heart of Arashiyama, we find the iconic Togetsukyo Bridge, or 'Moon Crossing Bridge' inviting us to cross its length. Our rickshaw makes a start over the historic structure, originally built during the Heian Period, now standing gracefully rebuilt, its structure resonating with timeless elegance." /
"As we cross, our guide's voice harmonizes with the gentle rumble of the Hozu River beneath us, sharing tales of the bridge's historical significance and the breathtaking scenes it gifts every spring and autumn. His words bring the landscape to life, painting the air with images of cherry blossoms and colorful fall foliage." /
"His recitation of Yamada Norifusa's poem, where the poet likens the view from the bridge to a 'touchable mist,' makes us appreciate the bridge's mesmerizing charm even more. As we glide over the bridge, we watch as locals and tourists alike partake in leisurely riverboat rides beneath us, their enjoyment adding vibrancy to the tranquil scene." /
"Once we reach the far end of the bridge, we decide to indulge in Arashiyama's famous tofu culture again, finding ourselves drawn to a nearby restaurant's offer of yudofu and an intriguing tofu ice cream. The unusual yet delicious blend of velvety tofu, sweet cream, and a hint of pure green matcha make for a memorable dessert." /
"Having satiated our appetites, we mount our bicycles again, ready to explore the soothing allure of Arashiyama more intimately. We follow a scenic path along the Hozu River, the soft gurgle of the water, the rustle of leaves above, and the occasional shared laughter from other path users creating a delightful soundtrack to our extraordinarily ordinary day in the heart of Kyoto.",

"Our Kyoto journey, punctuated by serene temples and bustling markets, brings us next to the Chion-in Temple, the headquarters of the Jodo-shu sect of Buddhism. As our rickshaw begins its slow ascent up the hill, our ever-cheerful guide fills us in on the temple's history, dating back to its construction in 1234 under the patronage of retired Emperor Honen." /
"Our attention is immediately seized by the imposing Sanmon gate, an architectural marvel built in 1621. Our guide shares that it is indeed the largest wooden gate in Japan, its grandeur immortalized in a famous print by Hiroshige. The gate towers over the landscape, serving as both a majestic gateway and a testament to the temple's importance." /
"Within the hallowed temple grounds, our footsteps lead us to the Miedo Hall, reputedly housing an image of Honen. Revered by devotees and tourists alike, the hall is often a space for quiet meditation and prayer, inviting a profound silence that draws a semblance of peace in the heart of every visitor." /
"Our guide with a gentle nudge steers us towards another marvel — the largest bell in Japan residing here within the temple's bounds. Proudly weighing in at a staggering 74 tons, the resonant sound, which requires the collective efforts of 17 monks on New Year's eve to summon, is said to reverberate throughout Kyoto, welcoming the new year." /
"After an enlightening tour of the temple, we seek reprieve at the temple tea-house, allowing the pacifying warmth of the matcha tea to seep tranquillity into our senses. The ritualistic pouring and sipping offer a surprisingly comforting experience, revitalizing us for further exploration." /
"Once we part ways with our rickshaw, we embrace the freedom of bicycling, gliding down the hill from the temple at our own pace, soaking in the calm of the surrounding nature, punctuated by the ethereal chirps of hidden birds. With every pedal, we are rendered more in tune with Kyoto's spiritual embrace, the quiet whispers of the Chion-in Temple fresh in our hearts.",

"As we descend from Chion-in Temple's sacred tranquillity, the rickshaw picks its way through Kyoto's picturesque avenues towards the famous Fushimi Inari Shrine. A series of vermilion torii gates captures our awe. They array up the trail, straddling the path up the eponymous mountain and beckoning us into an earthly embrace of tranquility." /
"Our guide explains with heartfelt clarity that Fushimi Inari is the paramount shrine dedicated to Inari, the Shinto god of rice. Intertwined with the fate and fortune of Japanese businesses, each vibrant torii gate we gaze upon signifies gratitude and hope for prosperity, donated as part of the 'Sengu' concept." /
"A fascinating part of the shrine's history, captured aptly by our guide, is that its original structures were harked back to 711 AD. Although the incarnation we stand before dates back to 1499, the area still pulses with the ancient spirit and customs of a time long past." /
"The unique essence of Fushimi Inari extends beyond spirituality into the realm of culinary traditions. Piquing our curiosity and appetite, several vendors around the shrine sell Inari Sushi and Kitsune Udon, characterized by fried tofu — a tantalizing nod to the lore of foxes, who are said to have a penchant for the ingredient. This belief also manifests in the form of numerous fox statues dotted throughout the shrine, silently narrating this folklore." /
"Within the confines of the shrine, we observe a flurry of visitors participating in an ancient custom, Omikuji. Drawing random fortunes written on strips of paper, the air is filled with anticipation and soft rustles. A sense of camaraderie lodges itself among the visitors, especially those who tie an unfavorable fortune onto a tree or rack, seeking purification and a bit of empathetic company." /
"As our rickshaw tour concludes, we reclaim our bicycles, ready to explore the vibrant cherry blossom-dotted vicinity of the Fushimi Inari Shrine at leisure. With the shrine’s allure still fresh in our hearts, we pedal through Kyoto's sublime landscapes, each vermillion torii gate, each cherry blossom, and each tofu-infused delicacy weaving Kyoto's essence deeper within our hearts.",

"Following the vibrant trail of the vermilion torii gates, we veer away from Fushimi Inari Shrine towards another renowned marvel—Kiyomizu-dera Temple, the Pure Water Temple. Our rickshaw winds its way up to the historic temple, the journey uphill leaving us breathless in more ways than one." /
"The temple, founded in 778, stands timelessly against Kyoto's skyline, embodying centuries of devout faith and serene resilience. The classic wooden stage, projecting from the main hall, offers us an arresting view of Kyoto's cityscape peppered with vibrant cherry trees." /
"Inside the temple, our jovial guide leads us in paying homage to Kannon, the Buddhist goddess of mercy. The soothing gurgle of the Otawa Waterfall, believed to grant wishes, lends mystical undertones to our exploration. Eager visitors, like us, gather to drink from the revered waterfall, hopeful for the fulfillment of their wishes." /
"As we wander through the temple grounds, the combined scents of incense smoke and wooden structures provide an olfactory backdrop to our cultural discovery. Some visitors are engaged in lighting incense, while some pull up the heavy ropes of the temple bells sending a deep sonorous echo reverberating around, and others quietly engage in drawing Omikuji—these Buddhist rituals adding to the soulful ambience of this ancient place." /
"After historical and spiritual explorations, we whet our appetite for culinary ventures. Nearby the temple, a traditional sweet shop attracts us with tray after tray of yatsuhashi, a traditional Kyoto sweet. Excited, we try the sweet, tasting the soft rice flour wrap seasoned with cinnamon and filled with sweet red bean paste—a delightful burst of flavors that pays tribute to Kyoto's rich gastronomical traditions." /
"Once we leave the rickshaw behind, our bicycles become our companions for a more intimate exploration of the extensive temple grounds. We pedal uphill, the effort fueling our eagerness for the arresting panoramic views promised at the top. As we reach the heights, the vista of Kyoto sprawling beneath us brings a comforting roundness to our exploration, the urban sprawl framed by fragrant cherry blossoms and the historic beauty of Kiyomizu-dera. Through the sweat and the serenity, the sweet treats and the soulful connections—we discover another part of Kyoto's multifaceted appeal."
    )

    override fun Config.end() =
    "Our sightseeing tour continues, steeped in a blend of rich history and enchanting narratives, as we make our way towards the Path of Love. Part of the UNESCO-certified Otowa-san Kiyomizu-dera complex, this picturesque uphill path is a local gem, steeped in lovely folklore." /
"Our jovial guide regales us with tales of how couples who walk hand-in-hand along this path will have their love wishes come true. Inspired by the stories, we eagerly embark on this popular path, its charm heightened by the surrounding cherry blossom trees that bloom vibrantly in spring, casting a beautiful pink hue overhead." /
"The timeless words of Japanese poet Ryōkan Taigu come to mind, as if narrating our current experience, 'In all the world, there's no place I'd rather be than here, walking on this path of love wrapped in the light of the spring sun.' We reflect on the poet's words as we absorb the soft streams of sunlight filtering through the branches, dappling the path with warm shadows." /
"Nestled nearby, local vendors greet us with friendly smiles and an enticing offer to partake in the region's culinary delights - the delicate yuba, uniquely made from tofu skin, and Kyoto's ceremonial matcha green tea. As we savour these treats, we note other visitors, making heartfelt wishes before starting their path journey, tying written prayers on trees or capturing moments under the cherry blossom shower." /
"Our rickshaw ride soon morphs into a serene bicycle exploration, allowing us a self-paced journey along the beloved Path of Love. The tranquillity of the scene, watched over by blooming Sakura and complimented by nature's melodic symphony, creates a perfect romantic canvas. It's an opportunity to appreciate the scenic beauty or perhaps even cherish a personal wish for love. With every pedal stroke, we weave ourselves closer into Kyoto's magical tapestry, the essence of love casting a delicate rosé tint over our shared adventure." /
"As the sun begins to dip low in the sky, casting long, artistic shadows across the cityscape, we find ourselves concluding our extraordinary sightseeing tour. Our rickshaw ride, charmed by the delightful company of our jovial middle-aged guide, has transformed the city’s streets, shrines, temples, and gardens into a vibrant tapestry of stories and experiences." /
"His hearty laughter still echoes in our ears as tales of emperors, samurais, geishas, and philosophers blend seamlessly with the history of architectural marvels and natural spectacles. His shared insights, anecdotes, and deep-rooted love for Kyoto have only served to magnify our own experience of the city’s unique rhythm." /
"Separately, our individual explorations on bicycles have afforded us exclusive, leisurely moments of serenity. The gentle rustle of leaves, the whisper of the wind, and the hypnotic trickle of sacred springs have been the perfect accompaniment to the silent strokes of our bicycle wheels. Embracing the tranquil beauty of the surroundings at our own pace, we’ve managed to contour a delicate interface between the city’s ethos and our own introspections." /
"The landscapes we've traversed, the foods we've savored, the fragrant air we've inhaled—all have composed an unforgettable symphony of sensations that has deepened our connection to Kyoto and its enchanted charisma. From the resplendent golden Kinkaku-ji and silver Ginkaku-ji temples to the panoramic views from the enchanting Togetsukyo Bridge; from the mesmerizing beauty of the Arashiyama Bamboo Grove to the mystical serenity of the Path of Love, our journey has unfolded like a meticulously crafted haiku, each experience a poignant verse." /
"As we pull our bicycles to a gentle stop, we take a moment to drink in the panoramic vista of city lights twinkling against the velvety evening silhouette of Kyoto’s mountains— a peaceful tableau that reminds us of the unforgettable journey we’ve embarked upon today. Steeped in the intoxicating blend of ancient traditions and modern rhythms, we know our farewell to Kyoto is merely a tender pause, for the magic and warmth of this city will always beckon us back, whispering through the cherry blossoms and the thrumming energy of its streets. Until then, our memories of Kyoto will shine inside our hearts, not unlike the city lights reflecting off the serene waters of Kamogawa, stirring a gentle yearning for more stories, more corners to explore, and more of Kyoto to fall in love with."
    }